### ISSUE TITLE
Multiple topics cause rebalancing conflict

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#10]
In Zookeeper under /consumers/<group>, there are three nodes:  ids, offsets, and owners.  Both offsets and owners are subdivided by topic; ids are not.  Because of this, when you listen to two different topics, the rebalancing routines think there are 2 consumers (two unique "ids" are generated), and only listens to half the topic partitions.

To reproduce:

* Create two topics in Kafka, each with two partitions.
* Create a consumer for each topic in your Go app.
* When the app starts, you'll see it grab all the partitions, then rebalance and grab half the partitions for each topic.

**Comment by sbowman** [comment]
Seems like there's two ways to solve this:

* Add the topic to the generated ID.
* Add the topic to the node under "ids", e.g. /consumers/mygroup/ids/mytopic/myid

I chose the latter, so it is consistent with "offsets" and "owners", though that makes "ids" inconsistent with the Java client.

Here's the patch:

```
diff --git a/consumer.go b/consumer.go
index 6f2f150..2125a57 100644
--- a/consumer.go
+++ b/consumer.go
@@ -381,7 +381,7 @@ func (c *Consumer) rebalance(claims Claims) (<-chan zk.Event, error) {
 	}
 
 	// Fetch consumer list
-	consumerIDs, watch, err := c.zoo.Consumers(c.group)
+	consumerIDs, watch, err := c.zoo.Consumers(c.group, c.topic)
 	if err != nil {
 		return nil, err
 	}
@@ -463,7 +463,7 @@ func (c *Consumer) claim(partitionID int32) (sarama.PartitionConsumer, error) {
 
 // Registers consumer with zookeeper
 func (c *Consumer) register() error {
-	if err := c.zoo.RegisterGroup(c.group); err != nil {
+	if err := c.zoo.RegisterGroup(c.group, c.topic); err != nil {
 		return err
 	}
 	if err := c.zoo.RegisterConsumer(c.group, c.id, c.topic); err != nil {
diff --git a/zk.go b/zk.go
index 55da244..342e972 100644
--- a/zk.go
+++ b/zk.go
@@ -34,8 +34,8 @@ func NewZK(servers []string, recvTimeout time.Duration) (*ZK, error) {
  *******************************************************************/
 
 // Consumers returns all active consumers within a group
-func (z *ZK) Consumers(group string) ([]string, <-chan zk.Event, error) {
-	root := "/consumers/" + group + "/ids"
+func (z *ZK) Consumers(group, topic string) ([]string, <-chan zk.Event, error) {
+	root := "/consumers/" + group + "/ids/" + topic
 	err := z.MkdirAll(root)
 	if err != nil {
 		return nil, nil, err
@@ -127,8 +127,8 @@ func (z *ZK) Offset(group, topic string, partitionID int32) (int64, error) {
 }
 
 // RegisterGroup creates/updates a group directory
-func (z *ZK) RegisterGroup(group string) error {
-	return z.MkdirAll("/consumers/" + group + "/ids")
+func (z *ZK) RegisterGroup(group, topic string) error {
+	return z.MkdirAll("/consumers/" + group + "/ids/" + topic)
 }
 
 // RegisterConsumer registers a new consumer within a group
@@ -143,12 +143,12 @@ func (z *ZK) RegisterConsumer(group, id, topic string) error {
 		return err
 	}
 
-	return z.Create("/consumers/"+group+"/ids/"+id, data, true)
+	return z.Create("/consumers/"+group+"/ids/"+topic+"/"+id, data, true)
 }
 
 // DeleteConsumer deletes the consumer from registry
-func (z *ZK) DeleteConsumer(group, id string) error {
-	return z.Delete("/consumers/"+group+"/ids/"+id, 0)
+func (z *ZK) DeleteConsumer(group, id, topic string) error {
+	return z.Delete("/consumers/"+group+"/ids/"+topic+"/"+id, 0)
 }
 
 /*******************************************************************
```

**Comment by dim** [comment]
So the zk paths are pre-defined by kafka, the same ones are used by the kafka's own consumer (Scala). The go consumer has the limitation that it can only consume one topic, i.e. you would have to create a separate consumer for each topic you are consuming. I was looking to lift this limitation over time, that's why I left it to the user to bake in the topic name into the consumer ID, but it probably makes sense to do it for now.

**Comment by dim** [comment]
Updated latest master to behave like kafka's native high-level consumer. https://github.com/bsm/sarama-cluster/commit/c22e38bb02fb963a6aec9c24d8916ef4fbf6d03a

It now supports multiple topics per cluster consumer, but please be aware of https://github.com/bsm/sarama-cluster/blob/c22e38bb02fb963a6aec9c24d8916ef4fbf6d03a/consumer.go#L105
