### ISSUE TITLE
Messages not being consumed after upgrading to v2.1.4 or master

### ISSUE THREAD

**Issue by F21** [bsm/sarama-cluster#100]
I recently upgrade to v2.1.4 from v2.1.3 and noticed that it no longer consumes messages properly in a consistent manner for a topic with 40 partitions. In both cases, I was using v1.11.0 for shopify/sarama.

For my test cluster, I have 1 zookeeper and 3 kafka brokers running in docker. Go is 1.8rc2.

Using the kafka consumer script, I can see that the messages were published to the topic.

I have added some `fmt.Println()`s to parts of the code base and I can see that sometimes `subs` returned [here](https://github.com/bsm/sarama-cluster/blob/737c8daca929f8d033f9b3adc78a840ca6977ac0/consumer.go#L235) can be empty.

I haven't had time to dig in further, but I hope that is a useful starting point!

**Comment by F21** [comment]
A bit more digging: It looks like this is due to the changes in f78b41464a39980a2bca18b109527b88e82dfaec. I added some `printf()`s and `allTopics` is missing the topic I subscribed to.

**Comment by F21** [comment]
Ok, I can pin point the root of the problem. In my case, I am creating the topic and subscribing to it immediately. However, `allTopics` is populated using `c.client.Topics()`: https://github.com/bsm/sarama-cluster/blob/737c8daca929f8d033f9b3adc78a840ca6977ac0/consumer.go#L447

`Topics()` uses cached metadata and the metadata is refreshed based on `Config.Metadata.RefreshFrequency`, which is 10 minutes by default.

A work around would be to set this a low value, like 1 second in my config, but this would probably cause performance problems.

Would it be possible to somehow have the behavior of 2.1.3?

**Comment by F21** [comment]
Code demonstrating the problem is in this repo: https://github.com/F21/kafka-test

**Comment by dim** [comment]
Thanks, good point, I will update.

**Comment by dim** [comment]
Could you please check https://github.com/bsm/sarama-cluster/commit/7fcb1d74bc3aa45ab92dafdb7be491d1f1515af0. I will release as v2.1.5 if successful

**Comment by F21** [comment]
I just tried 7fcb1d74bc3aa45ab92dafdb7be491d1f1515af0, but it is inconsistent. Sometimes, it works, some times, it doesn't. I guess it's some sort of a race condition. Because we're polling kafka to list the topics before subscription, if we create a topic in zookeeper and try to subscribe to it immediately, there is a race to see whether kafka will be able to see it.

**Comment by F21** [comment]
Maybe a solution is to decrease the strictness of `onlyConsumableTopics()` and include topics passed to the consumer even if kafka does not seem them yet.

**Comment by dim** [comment]
hey again, could you please take a look at https://github.com/bsm/sarama-cluster/pull/102, this should fix your problem too.

**Comment by dim** [comment]
Will create a new release shortly

**Comment by F21** [comment]
Awesome! Thanks for the quick fix! 😄
