### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by joaodlf** [bsm/sarama-cluster#105]
Sarama has a series of Examples in godocs (https://godoc.org/gopkg.in/Shopify/sarama.v1#pkg-examples)

Would it be possible to have something similar demonstrating Sarama-Cluster usage? The README mentions examples, but I can't seem to find any.

**Comment by dim** [comment]
How about https://github.com/bsm/sarama-cluster/commit/309783eefad2cf76d730a4cb42906e201e7ad12d

**Comment by joaodlf** [comment]
Looks good to me! Even learned something new from that!
