### ISSUE TITLE
Get the last processed message in a group or in a partition

### ISSUE THREAD

**Issue by krywen** [bsm/sarama-cluster#106]
In my case I only have 1 topic with 1 partition, 1 producer and 1 consumer.

In case the consumer fails, I want to be able to restart it and process all the messages since the last processed one. To achieve this I could re-process all the messages since OffsetOldest until I find one which has not been processed yet.

Is there a way to determine which was the oldest message non-processed by a (any) consumer of a topic/partition/group?
1. I've look at calling MarkOffset() and CommitOffset() after receiving every message, but I am not sure how to retrieve the oldest non committed offset.
2. In case I use the method 1., how do I check the marked metadata of a specific offset? 

Is this a viable usage of kafka and sarama-cluster?
Thank you

**Comment by dim** [comment]
> I've look at calling MarkOffset() and CommitOffset() after receiving every message, but I am not sure how to retrieve the oldest non committed offset.

You only need to call `MarkOffset` as `CommitOffset` will be called automatically every `Config.Consumer.Offsets.CommitInterval` (see https://godoc.org/github.com/Shopify/sarama#Config)

> I want to be able to restart it and process all the messages since the last processed one. To achieve this I could re-process all the messages since OffsetOldest until I find one which has not been processed yet.

That's exactly what sarama-cluster does for you. It will query Kafka for the latest processed offset of the specified consumer group ID and resume automatically, no manual intervention needed. Please see https://kafka.apache.org/documentation/#intro_consumers.
