### ISSUE TITLE
More than one consumer receive the same messages

### ISSUE THREAD

**Issue by hmgle** [bsm/sarama-cluster#108]
All the consumers are in the same group. It can be reproduced not always, try to stop and run the consumer hourly.
<img width="1390" alt="sarama-cluster" src="https://cloud.githubusercontent.com/assets/1779916/22780742/bee90a62-eefa-11e6-8ce8-3e6400495da2.png">

consumer.go:
```go
package main

import (
	"log"

	"github.com/Shopify/sarama"
	cluster "github.com/bsm/sarama-cluster"
)

func main() {
	config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true
	config.Consumer.Offsets.Initial = sarama.OffsetNewest
	c, err := cluster.NewConsumer([]string{"your broker addr"}, "group0", []string{"x1"}, config)
	if err != nil {
		log.Fatal(err)
	}
	for msg := range c.Messages() {
		log.Println(msg)
	}
}
```
producer.go:
```go
package main

import (
	"log"

	"github.com/Shopify/sarama"
)

func main() {
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Return.Successes = true
	p, err := sarama.NewSyncProducer([]string{"your broker addr"}, config)
	if err != nil {
		log.Fatal(err)
	}
	msg := &sarama.ProducerMessage{Topic: "x1", Key: sarama.StringEncoder("key"), Value: sarama.StringEncoder("1")}
	_, _, err = p.SendMessage(msg)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by dim** [comment]
Looks like you are not closing your consumer gracefully which will inevitably result in ACKed messages not being committed. Add a `defer c.Close()` to your client code *AND* catch interrupt signals to make sure your `main` func exits gracefully. Please also see the [Example](https://godoc.org/github.com/bsm/sarama-cluster#example-Consumer).

**Comment by dim** [comment]
Sorry, unrelated, but it looks like you are not marking offsets as being processed either, in which case there is no guarantee that a message will not be processed again after consumer restart.
