### ISSUE TITLE
Add `Consumer.Config()` so configuration can be validated

### ISSUE THREAD

**Issue by kerinin** [bsm/sarama-cluster#109]
I'm working on a wrapper around `Consumer` that exposes process metrics and it would be really helpful if the constructor could return an error if `Config.Group.Return.Notifications` was false (I'm using notifications to register/unregister metrics).  The problem is that I can't access the config of a given `Consumer`.  The method exists on the underlying Sarama consumer, FWIW: https://godoc.org/github.com/Shopify/sarama#Client

**Comment by dim** [comment]
Hmm, so it's not something sarama offers on [Consumer](https://godoc.org/github.com/Shopify/sarama#Consumer), but only on [Client](https://godoc.org/github.com/Shopify/sarama#Client) level. I'm happy to do the same, but could you please add a PR which exposes Config [here](https://github.com/bsm/sarama-cluster/blob/master/client.go)? That would be much appreciated.

**Comment by dim** [comment]
Is this still an issue? Do you still require it? Please re-open if so
