### ISSUE TITLE
What's the behaviour when the log file the consumer is consuming got deleted?

### ISSUE THREAD

**Issue by nomoonx** [bsm/sarama-cluster#113]
Hi,

I'm using Kafka 0.9.0.1 and I let Kafka to delete the log file every one hour. So when the deletion happened, the speed of the consumer group would drop from 10k/s to 200+/s or even lost the connection. Is there any solution to this situation?

**Comment by dim** [comment]
I suspect that your disk is the problem, did you measure/profile IO & CPU during these deletions? I doubt that it's a client problem, but - if you don't find anything - you can raise a ticket with [sarama](https://github.com/Shopify/sarama) itself
