### ISSUE TITLE
Retain offsets while consumer running but not receiving messages

### ISSUE THREAD

**Issue by vanillechai** [bsm/sarama-cluster#116]
When a consumer has not received a message for a certain amount of time (more than offset.retention.minutes) in a partition, Kafka expires this offset. If the consumer is then restarted, it will re-consume all available messages on that partition.

In the python client, the solution is to recommit periodically the last known offsets or enable auto commit. This prevents offset expiry as long as the client is running, even if it receives no messages on a partition for longer than the retention time.

I failed to copy this behaviour with sarama-cluster. Simply marking the current offsets does not re-commit them to Kafka; they will still expire. Setting the consumer.Offsets.Retention to a high value does not solve the underlying problem, because this time is still independent of the consumer lifetime.

How could I achieve it that consumers will not lose their offsets as long as they are running? Can I do a "recommit" with sarama-cluster?

**Comment by dim** [comment]
I think this should solve it: https://github.com/bsm/sarama-cluster/commit/96927bc1831fb883c7903d3d48f5212041c9b1b5. I will merge once CI builds. This forces the lib to commit on every commit interval instead of tracing "dirty" state. The overhead of this should be negligible.

**Comment by dim** [comment]
Fixed in #117

**Comment by vanillechai** [comment]
I tested with e92a2f from #117 and the offsets are no longer lost. Great, thanks for the quick response!

**Comment by dim** [comment]
@vanillechai I had to revert this PR partially because of #124. Instead, the cluster now only commits offsets when at least 50% of Consumer.Offset.Retention have passed since the last commit. Please let me know if that suits you.
