### ISSUE TITLE
Error: Offset's topic has not yet been created

### ISSUE THREAD

**Issue by mengzhuo** [bsm/sarama-cluster#118]
hi, I'm try to use sarama-cluster in my multi-consumer on one topic project.
However when I attach it to my kafka 0.10 brokers, it says "Offset's topic has not yet been created"

```go
func main() {

        ccfg := cluster.NewConfig()
        ccfg.Consumer.Return.Errors = true
        ccfg.Group.Return.Notifications = true
        // setting topics, brokers, blah... blah...blah...
        consumer, err = cluster.NewConsumer(cfg.Kafka.Brokers,
                cfg.Kafka.GroupID, topics, ccfg)
         if err != nil {
              log.Print(err) // <- Offset's topic has not yet been created
          }
}
```

Go version: 1.8
Kafka version: 0.10
sarama-cluster version: 5d8c11085c875b3155870da9ba6be706429a95dc
sarama version: 3efb95dad8fbcd194d3c06f7b9c40eabeb719b36

**Comment by dim** [comment]
Sorry, I don't quite follow. Could you please provide more details.

**Comment by mengzhuo** [comment]
it's been updated.

**Comment by dim** [comment]
Hey, so yes, you have a few option:

1. You pre-create the topics before you consume them
2. You set the `auto.create.topics.enable` to true on your Kafka brokers
3. You use `config.Group.Topics.Whitelist` (see [docs](https://godoc.org/github.com/bsm/sarama-cluster#Config)) and supply `nil` as topics to `cluster.NewConsumer`.

**Comment by dim** [comment]
Oh, sorry, I misread, it seems the error refers to Kafka error 15, which is `GROUP_COORDINATOR_NOT_AVAILABLE`, see https://kafka.apache.org/protocol. It looks like your cluster is unable to form a quorum, this is not a client but a server error, please check the server logs.

**Comment by mengzhuo** [comment]
Just an update for anyone stumble into this issue.

Root cause: IT guys removed leader node of __consumer_offsets without reassign.
1. check your leader status of __consumer_offsets topic
2. resume the previous leader node if leader is -1.
3. wait for reassign, make sure every partition has new leader.

**Comment by zirkome** [comment]
It may be an old issue but I ran into this error today with a local 1-node Kafka cluster. The solution was to set `offsets.topic.replication.factor` to `1`.

From the [0.11.0.0 changelog](https://kafka.apache.org/documentation/#upgrade_1100_notable):
> The `offsets.topic.replication.factor` broker config is now enforced upon auto topic creation. Internal auto topic creation will fail with a `GROUP_COORDINATOR_NOT_AVAILABLE` error until the cluster size meets this replication factor requirement.
