### ISSUE TITLE
Exposing the topicPartition struct

### ISSUE THREAD

**Issue by jerrygb** [bsm/sarama-cluster#122]
Currently, there is an available function for Marking multiple offsets using a consumer.

Is it possible to expose the topicPartition struct so we can utilize this? Also, could you please let us know if there is an alternative?

**Reference:** 
https://gowalker.org/gopkg.in/bsm/sarama-cluster.v2#NewOffsetStash
https://gowalker.org/gopkg.in/bsm/sarama-cluster.v2#Consumer_MarkOffsets

Thank you.

**Comment by dim** [comment]
Sorry, I don't understand the question? Isn't `OffsetStash` exactly what you need?

**Comment by jerrygb** [comment]
Hmm, true after going through the code, guess thats exactly what I need, my bad. I didnt notice the `MarkoffSets` on OffsetStash struct.

Please close this issue. 👍
