### ISSUE TITLE
#Partitions change not reflected on consumer client 

### ISSUE THREAD

**Issue by vramakrishnan** [bsm/sarama-cluster#126]
In my tests, I increased the partitions from 6 to 8 on kaka cluster.
In took several minutes for consumer (based on sarama-cluster) to be notified. 

I am sure there is a way to tweak the meta-data refresh interval to order of secs on the Kaka client side ?  Can someone please share the config params to do the same.

**Comment by vramakrishnan** [comment]
I tried setting "    config.Metadata.RefreshFrequency = time.Second * 15".

With this, I see these logs to refresh every 15seconds but partition change is not getting reflected on Client side until about 10mins later.

2017/05/10 01:13:50 client/metadata fetching metadata for all topics from broker localhost:9092
2017/05/10 01:14:05 client/metadata fetching metadata for all topics from broker localhost:9092

**Comment by dim** [comment]
The consumers perform continuous heartbeats against the coordinator (broker). A rebalance is triggered as soon as one of those heartbeats fails, which is usually to a generation change. 

There may be two reasons for your issue and I would appreciate some help with debugging this:

1. Kafka broker is not triggering a rebalance for 10 minutes, which is probably a setting on the server. 
2. On rebalance, sarama cluster is not forcing a meta-data refresh and - while Kafka is instantly triggering a rebalance - stale data may be used.

Could you enable sarama debug logging or notifications and see if rebalances are being triggered on partition changes?

**Comment by vramakrishnan** [comment]
Thanks for the prompt response.

#1 Is there specific kafka server setting I need to check ?

#2 I have enabled verbose logging and initialized sarama logger. 
Those output of metadata refresh are seen due to this. Is there more setting to enable debug log ? Please let me know.

**Comment by vramakrishnan** [comment]
Looked at Kafka-manager, after addinging more partitions, the new partitions were not assigned to existing consumer pool.  

This appears to be server side config setting. Will debug more and update the thread. Only after this assignment, I would expect clients to get updated (via refresh) metadata info with rebalancing.

csostest.uswest

Partition	LogSize	Consumer Offset	Lag	Consumer Instance Owner
0	32	32	0	csos_server-20cdab17-21ff-41e3-ab64-cfd9616ee23e:/10.1.1.1
1	2	2	0	csos_server-d5bbe931-1cc5-475f-b7b5-48cf08b55384:/10.1.1.1
2	0	-1		
3	0	-1

**Comment by dim** [comment]
I will close for now, please re-open.

**Comment by PoacherBro** [comment]
@vramakrishnan hi, have you found out the cause of that problem? I also encountered this issue with the latest cluster version, but after I added new partition in kafka-manager, the producer can send to the new one, while no reflection in consumer side. 
Not sure you have fig out, and if yes, appreciate you can share. Thanks.
