### ISSUE TITLE
Consumer: lz4.Read: invalid header checksum

### ISSUE THREAD

**Issue by Typositoire** [bsm/sarama-cluster#127]
I've got a topic created with a Java Producer 0.10.2.1 with LZ4 Compression but when ever I try to read it using this library I get this:

```
2017/05/14 14:41:38 Error: kafka: error while consuming <TOPIC>/<PARTITION>: lz4.Read: invalid header checksum: got 26 expected 130
```

I've looked and I seem to be the only hitting this issue ?

EDIT: I can read from other topics correctly (None-LZ4) but I haven't tried other compression types.

**Comment by Typositoire** [comment]
Ok so i'm just retarded... Default `cluster.Config` is not set to `sarama.V0_10_X_X`

**Comment by yixinGod** [comment]
please tell me how to resolve this problem!!! 
thanks

**Comment by dim** [comment]
@yixinGod this is not a sarama-cluster but a core https://github.com/Shopify/sarama "issue". You need to set the protocol version to the relevant value, i.e. `config.Version= sarama.V...`
