### ISSUE TITLE
Achieve perf advantage when committing with offsetstash

### ISSUE THREAD

**Issue by jerrygb** [bsm/sarama-cluster#128]
Hi,

This is once again a question.

I would like to know if there is anyway to achieve performance advantage when committing offsets using [OffsetStash](https://godoc.org/github.com/bsm/sarama-cluster#OffsetStash) for a single partition. I had noticed that we do create a snapshot of entire partition map in the function [CommitOffsets()] (https://godoc.org/github.com/bsm/sarama-cluster#Consumer.CommitOffsets) which makes sense assuming we calling at the end of the Commit Interval. 

But I wanted to know if there is any other efficient way, assuming that the app is intelligent enough to maintain a secondary partitionMap due to the nature of the problem we trying to solve, is there any efficient mechanism to commit offsets.

Additionally, perhaps only the last offset within that partition for the batch of message processed? I am not entirely sure if that is a good pattern though.

We are trying to achieve the breakoff and achieve performance wherever possible, since we are trying to process approx. 400K messages/sec, based on earlier implementation on java.

Currently this is what I am doing,

```go
offsetStash := cluster.NewOffsetStash()

// Process a specific partition from the map
for p, q := range partitionQueues {
   while(not end of message in partition queue) {
      // Process each message in the secondary queue, separate from the consumer loop (chan consumer.Messages() )
      // If msg is good, add to offsetstash using consumer.MarkOffsets(offsetStash)
      // Else if msg is no good, break the loop and go to the next queue, since there is no point in processing a later offset, afaik.
   }
   // Finally, commit the offsets, since we dont want to process them again.
   err := consumer.CommitOffsets()
   if err != nil {
      logger.Error("Error committing offsets: ", err.Error(), " for Partition: ", p)
      logger.Warn("Will retry marking offsets for Partition: ", p, ".")
      continue
   }
}
```
There are multiple threads for our consumers but when we commit the offsets, we do ensure that we have right consumer, that is assigned to the partition. We use the default `StrategyRange` as the group partition strategy.

Thank you.

**Comment by dim** [comment]
You don't need to call `consumer.CommitOffsets()` at all, the consumers commit offsets automatically every `config.Consumer.Offsets.CommitInterval`. It maintains a list of "marked" offsets internally, please see https://godoc.org/github.com/bsm/sarama-cluster#Consumer.MarkOffsets for details.

The `OffsetStash` helps to mark multiple offsets at once, but you must use it in combination with https://godoc.org/github.com/bsm/sarama-cluster#Consumer.MarkOffsets.

Please see the README or the Example of https://godoc.org/github.com/bsm/sarama-cluster#Consumer for more details

**Comment by jerrygb** [comment]
Hi @dim,

I understand that it would commit at the end of interval, but we would like to have slightly more control over the commits due to the nature of the problem.

We would like to control the frequency of the commits dynamically as well, based on the load.

Thank you.

**Comment by dim** [comment]
Yes, calling `CommitOffsets()` allows you to trigger a manual commit, but you still need to call `MarkOffset` (or `MarkOffsets`) first.

**Comment by jerrygb** [comment]
Sorry, I wasnt clear. Yes, I do understand that we do need to mark it before committing, as shown in the example. 

If we look at the commitoffsets currently, 

```go
func (c *Consumer) CommitOffsets() error {
	c.commitMu.Lock()
	defer c.commitMu.Unlock()

	req := &sarama.OffsetCommitRequest{
		Version:                 2,
		ConsumerGroup:           c.groupID,
		ConsumerGroupGeneration: c.generationID,
		ConsumerID:              c.memberID,
		RetentionTime:           -1,
	}

	if rt := c.client.config.Consumer.Offsets.Retention; rt != 0 {
		req.RetentionTime = int64(rt / time.Millisecond)
	}

	snap := c.subs.Snapshot()
	for tp, state := range snap {
		req.AddBlock(tp.Topic, tp.Partition, state.Info.Offset, 0, state.Info.Metadata)
	}
```

It takes a snapshot of entire partitionqueue, which is not required in our scenario since we commit the offsets per partition, more like the native PartitionConsumer sarama client.

So I was wondering if there similar function in sarama-cluster as well.

**Comment by dim** [comment]
No, but that is not really an issue. The native sarama OffsetManager behaves exactly the same under the hood, except that it does only commit one block at a time, while sarama-cluster.Consumer can commit multiple topic/partitions in a single request. 

To "serialise" the commit order, you could stash your offsets by partition (e.g. `map[int32]*cluster.OffsetStash`) and then mark/commit sequentially.

**Comment by jerrygb** [comment]
Thank you @dim. Yes, we were actually creating a secondary partitionMap with offsets that can be marked using OffsetStash precisely as you mentioned. But was wondering if there is good mark them and achieve performance, such as marking only the last offset for the specific partition.

Good to know about batch commit of offsets with sarama-cluster. I suppose when using this method of batching offsets, performance criteria is already taken care of.

**Comment by dim** [comment]
> ... marking only the last offset for the specific partition
no, there would not be any performance benefit as this is exactly what the consumer's internal offset state does for you. so, yes, it's taken care of :)

**Comment by jerrygb** [comment]
Thank you.
