### ISSUE TITLE
Access to Offset metadata

### ISSUE THREAD

**Issue by sp1ff** [bsm/sarama-cluster#129]
When committing an offset for a partition, I can specify metadata along with the offset in MarkOffset & MarkPartitionOffset, but I can't see how to get at the metadata that was committed most recently for a given topic/partition when my consumer starts up. It's there (in subs.data[topicPartition{topic: topic, part}].state.Info.Metadata), but it's not exported. Is this supported somehow?

I ask because I'm using "semantic partitioning" and I'd like to use the metadata to store & recover processor state for the partition on startup.

**Comment by dim** [comment]
So I have no issue in exposing Metadata to the user but I am not entirely sure how useful that would be. The metadata is retrieved from the broker on rebalance. The only way for a user to even know that a rebalance has occurred is via the `Notifications()` channel. I could emit the metadata as part of that, but I am not sure how useful this would be.

**Comment by sp1ff** [comment]
I see. The utility lies in being able to commit your per-partition consumer state along with the offsets.

Here's a use case. Suppose I have a topic containing events corresponding to page views on my site. The event contains a member id, and the topic is partitioned by page. I want to count overall page views per member. It's a big site, so I have many partitions in my topic, and I have multiple processes in my consumer group slurping up that topic. For each partition, I'm going to need to count the number of events for each member, and periodically:

a) commit my offsets
b) produce to another topic for a downstream consumer; this topic will be keyed by member id (so the downstream consumer can be sure that all of a given member's counts go to one partition; this is where the final count will be computed)

Suppose one of my consumers crashes/goes offline. A re-balance will be triggered, and whatever consumer gets the dead consumer's partitions can read their offsets & keep going. However, the old consumer's counts (or any other state) will be lost. Sure, we could shove state into some central datastore (keyed by partition id, say) ,or we could arrange our calculation to not retain state post-offset commit, but being able to commit it along with our offsets, and "re-hydrate" the new consumer on re-balance is convenient. I believe this was the intended use of the metadata in the first place.

Just a thought-- call this a feature request. Thanks.

**Comment by dim** [comment]
@sp1ff thanks for the detailed explanation, makes sense. The issue I have is still: how do you want to "re-hydrate" the new consumer? Assuming a new consumer is being assigned a series of topics/partitions, how do you want to handle this assignment? Subscribing to `Notifications` may not be sufficient as new messages may flow in before the notification is emitted. I can only think of a registrable callback, but that seems clumsy.

Thoughts?

**Comment by sp1ff** [comment]
Sorry Dimitrij-- got pulled off onto something else.

So I thought it could come along with the notification of a rebalance, but
I didn't realize that my consumer might get messages for the new
partition(s) before that notification arrives. That's a problem. Since the
partition ID comes along with the message, I suppose the consumer
*could* detect
that this is new, and buffer the message until the relevant notification
arrives, but that's really ugly.

Something I did on my own consumer group implementation to address that was
to setup one channel for everything. So, instead of a switch like this:

              select {
                case msg, ok := <-consumer.Messages():
                    // Do stuff with a new message...
                case err, more := <-consumer.Errors():
                    // Do stuff with a new error...
                case ntf, ok := <-consumer.Notifications():
                    // Do stuff with a new notification...

I do this:

for event := range consumer.Messages() {
switch e := event.(type) {
case Message:
                    // Do stuff with a new message
case error:
                    // Do stuff with a new error...
case Notificiation:
                    // etc
}

Coming from C++, the typecasting feels weird to me, but the single channel
lets me guarantee that notification of a new partition assignment will
arrive before any messages from said partition.

**Comment by GuillaumeBailey** [comment]
I would have another use for this. It is useful for a designated Kafka client to be able to look at the most recent committed offsets for the purposes of calculating backlog/queue depth. The design (at least in github.com/uber/cherami-server) would be to have the consumer of the 0th partition calculate the overall backlog and publish a metric.

**Comment by dim** [comment]
@GuillaumeBailey you can already do this through normal [sarama](https://godoc.org/github.com/Shopify/sarama#Broker.FetchOffset), e.g. 

```
const groupID = "my-consumer-group"
broker, _ := client.Coordinator(groupID)
req := &OffsetFetchRequest{ConsumerGroup: groupID}
req.AddPartition("my-topic", 0)
req.AddPartition("my-topic", 1)
offsets, _ := broker.FetchOffset(req)
...
```

**Comment by dim** [comment]
@sp1ff you should check out #137 - I think you are both asking for the same thing. I will create a separate PR for this.

**Comment by dim** [comment]
Created the PR, closing this one
