### ISSUE TITLE
Q: How to handle consumer errors & notifications?

### ISSUE THREAD

**Issue by vanillechai** [bsm/sarama-cluster#132]
The doc for Consumer.Errors() says:
`If you want to implement any custom error handling, set your config's Consumer.Return.Errors setting to true, and read from this channel. `

A few questions regarding this:
* When do I have to implement any custom error handling?
* "custom error handling" implies that there is already some default error handling. What errors are already handled by sarama-cluster?
* Will setting Consumer.Return.Errors to true disable the default error handling?
* Can you point me to any example of custom error handling? All examples I've found so far only log received errors in a simple loop. What's the point of this?

For Consumer.Notification(), the doc says:
`Notifications will only be emitted over this channel, if your config's Group.Return.Notifications setting to true. `

* Do I understand this right: Will sarama-cluster handle any rebalancing on its own?
* Will setting Return.Notifications to true simply notify that rebalancing is happening, or will it change sarama-cluster's behavior of handling rebalancing?
* Can you point me to any example of notification handling? All examples I've found so far only log received notifications in a simple loop. What's the point of this (apart from being notified)?

**Comment by dim** [comment]
Hey,

The `Errors` channel propagates underlying errors from the underlying [PartitionConsumer](https://godoc.org/github.com/Shopify/sarama#PartitionConsumer). By default these errors are logged but can instead be emitted to the `Errors` channel.

Yes, sarama-cluster handle any rebalancing on its own, that's the main purpose of this (add-on) library. Setting `Return.Notifications` to true, will simply emit notifications, there is no change in operational  functionality (same for `Return.Errors`). There is no example for it, but - apart from logging - emitting notifications can be useful for instrumentation, i.e. "how many times does our cluster rebalance?" or "are actually all partitions being consumed?", etc.

PS: I am looking for help with documentation. I would greatly appreciate if you could submit a pull-request with additional information and more details, where necessary. Thanks
