### ISSUE TITLE
Break for loop

### ISSUE THREAD

**Issue by iDiogenes** [bsm/sarama-cluster#134]
Hello and thank you for a great extension to Shopify's sarama.

I have a situation where I need to start at the beginning of the topic, consume all its messages and then proceed on in the program with those messages. I should note, that no new messages are being added to the topic while this is happening. In other words, the number of messages is fixed at the start of the program. However, I have run into several issues trying to do this. 

The obvious first approach (using your for loop example in the README) was to add a `default:` section to the select statement with a break. However, `default` would trigger even when there were messages still in the topic to be consumed. I also thought using `len()` before the loop might work and loop until all the messages had been consumed. Unfortunately, `len()` returns 0, so that is not an option. Finally, if I remove the select statement it will pull all the messages, but of course, it deadlocks at the end because of the unbuffered channel waiting for a message.

I also thought about doing the loop in a goroutine and tracking when it finally deadlocks, but that seems flawed and trying to use go in a way it was not intended. 

Is there any way to accomplish the aforementioned functionality, or am I simply trying to use sarama-cluster in a way it was not designed? 

Thanks in advance for any assistance or insight!

**Comment by dim** [comment]
Why not something like:

```
timeout := time.NewTimer(time.Second)
defer timeout.Stop()

MessageLoop:
for { 
  select {
  case <-c.Messages():
    ... 
    timer.Reset(time.Second)
  case <-timeout.C:
    break MessageLoop
  }
}
```

This would exit the loop after a "deadlock" of 1s?

**Comment by iDiogenes** [comment]
@dim That worked wonderfully. Thank you.
