### ISSUE TITLE
Rebalance and message out of order

### ISSUE THREAD

**Issue by isethi** [bsm/sarama-cluster#137]
I am listening to the messages and notifications channel for consumer groups. And I get the messages from new notifications before I get the rebalance notification. Is that expected behavior?

**Comment by dim** [comment]
Yes, the notifications channel is buffered so there is currently no way for sarama-cluster to ensure that the notification has been consumed. I am happy to change this behaviour in the next release though.

**Comment by dim** [comment]
Created the PR, closing this one
