### ISSUE TITLE
Multiple Consumer Groups with Failure Recovery Support

### ISSUE THREAD

**Issue by mohigup** [bsm/sarama-cluster#138]
Question

Versions

Sarama Version: 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.8

Problem Description

I am looking to use sarama-cluster Library for Kafka and wanted to create 2 consumer groups. Each of these groups will poll to Topic and request messages. If there is a message A, it has to sent to both consumer groups. Please advise on following

- Does current version supports sending same data to each of the consumer groups as mentioned above?
- Does the library supports consumer group recovery on failure if a consumer group goes down?

**Comment by seifer** [comment]
+1 for the first question? I have two consumers with different consumer group and clients with one topic. I expect that both consumers will receive every message from topic, but it does not work now :(

**Comment by dim** [comment]
I don't see a problem with that. Messages are consumed by exactly one consumer within a group. As long as you name your two groups differently, it should work as expected. Please see https://kafka.apache.org/documentation/#intro_consumers for more info
