### ISSUE TITLE
Message not consumed from Kafka

### ISSUE THREAD

**Issue by gauravsb** [bsm/sarama-cluster#139]
Hi, I am new to golang and I used sarama to read data from kafka. It worked fine. However, because the offset management was not there in sarama, I am trying to use sarama-cluster.
However, I am unable to consume messages as was possible when I was using sarama.

Here is my code 

```
        var logger = log.New(os.Stderr, "", log.LstdFlags)

        config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true

        sarama.Logger = logger

	// Create new consumer
	consumer, _ := cluster.NewConsumer(brokers, "test-group", []string{"my-topic-name"}, config)

	defer func() {
		if err := consumer.Close(); err != nil {
			panic(err)
		}
	}()

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	for {
		select {
		case err, more := <-consumer.Errors():
			if more {
				fmt.Println(err)
			}

		case messageFromKafka, more := <-consumer.Messages():
			if more {
				fmt.Fprintf(os.Stdout, "%s/%d/%d\t%s\t%s\n", messageFromKafka.Topic, messageFromKafka.Partition, messageFromKafka.Offset, messageFromKafka.Key, messageFromKafka.Value)
			}

		case ntf, more := <-consumer.Notifications():
			if more {
				fmt.Println("Rebalanced: %+v\n", ntf)
			}

		case <-signals:
			fmt.Println("Interrupt is detected")
			break
		}
	}
```

As per the logs, it seems to be connected as well :

```
2017/06/26 13:47:02 cluster/consumer sarama-f45d15bb-1492-4d21-96c4-63d6bebbeff9 consume "my-topic-name"/1 from -1
2017/06/26 13:47:02 cluster/consumer sarama-f45d15bb-1492-4d21-96c4-63d6bebbeff9 consume "my-topic-name"/0 from -1
2017/06/26 13:47:02 Connected to broker at xxx403.xxx:9092 (registered as #403)
2017/06/26 13:47:02 consumer/broker/403 added subscription to "my-topic-name"/1
2017/06/26 13:47:02 Connected to broker at xxx402.xxx:9092 (registered as #402)
2017/06/26 13:47:02 consumer/broker/402 added subscription to "my-topic-name"/0

```

Am I missing something here ?
What might be the potential reasons for this to fail ?

Please let me know if I can give you any more information.

PS : Similar code works fine with sarama.

**Comment by dim** [comment]
Hey, you didn't really mention what exactly the problem is? Which bit is
failing for you? The only mistake I can see is the `break` after consuming
signals, which will break out of the select but not the for loop.

**Comment by mohigup** [comment]
@gauravsb I tried the example provided in cmd/sarama-cluster-cli and it works for me. I noticed that you have added additional break statement.

**Comment by gauravsb** [comment]
Sorry for bothering. It seems to be working fine. Turns out that there some internal connection issue with kafka due to which it did not work.
