### ISSUE TITLE
Consume messages from beginning after calling MarkOffset in Consumer

### ISSUE THREAD

**Issue by mohigup** [bsm/sarama-cluster#140]
Hi,

I am using the example provided in **cmd/sarama-cluster-cli** and see that messages that are read have their offset marked using `consumer.MarkOffset(msg, "")`. After reading messages in the consumer, I want to read messages again after restart of consumer.

**Is it possible to read the messages again in the same consumer after restarting the consumer?**

I see that it is possible to do the same in the default implementation of consumer provided with Kafka tar i.e. after restart of kafka-console-consumer.sh, I can read the messages from beginning.

`bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning`

**Comment by dim** [comment]
@mohigup we had several discussion recently in https://github.com/bsm/sarama-cluster/issues/133#issuecomment-306146528. this is something that would require coordination between consumers within a group. to achieve this (cleanly), you need to:

1. stop all consumers
2. wipe the consumer group offsets
3. restart consumers
