### ISSUE TITLE
Offset Checker for Consumer Group

### ISSUE THREAD

**Issue by mohigup** [bsm/sarama-cluster#141]
Question

Versions

Sarama Version: 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.8

Problem Description

How to check the details of offsets consumed by consumers in a consumer group?
The existing tools provided in Kafka doesn't provide the feature for non java based clients.

**Comment by dim** [comment]
You can instrument your `Ack` calls and report offsets ack'd by the consumers. 

If you are looking for lag-reporting, this is not something you want to manage within your cluster, as you would be doing it N times. Kafka itself is providing a bin/kafka-consumer-groups.sh which you can use for instrumentation/monitoring/reporting. See https://kafka.apache.org/documentation/#basic_ops_consumer_lag

**Comment by mohigup** [comment]
@dim Thanks for the Reply. I did tried **kafka-consumer-groups.sh** but it doesn't work for non java based clients. Here is an example:

`bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group testgroup3`
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers)

`bin/kafka-consumer-groups.sh --list --bootstrap-server localhost:9092 `
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

**Comment by dim** [comment]
@mohigup sarama-cluster *is* using the Java consumer API and not zookeeper. I can see my consumer groups via `bin/kafka-consumer-groups.sh --list --bootstrap-server ...` just fine

**Comment by mohigup** [comment]
@dim. Apologies. I can see the consumer groups as well but the describe group isn't giving any information. Below is an example.

`bin/kafka-consumer-groups.sh --describe --bootstrap-server localhost:9092 --group testgroup3`
```
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
```


Also, If I try to see details in the topic, I see there are many partitions in the topic used to store offset information for consumer. However, I expected something similar would show in the previous command :(

`bin/kafka-topics.sh --describe --zookeeper localhost:2181 `

```
Topic:__consumer_offsets	PartitionCount:50	ReplicationFactor:1	Configs:segment.bytes=XXX,cleanup.policy=compact,compression.type=producer
	Topic: __consumer_offsets	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: __consumer_offsets	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
	........................ continued
	Topic: __consumer_offsets	Partition: 48	Leader: 0	Replicas: 0	Isr: 0
	Topic: __consumer_offsets	Partition: 49	Leader: 0	Replicas: 0	Isr: 0
```

**Comment by dim** [comment]
Looks as you are not consuming or your consumers have all stopped.

**Comment by mohigup** [comment]
The consumer is running but there were no new messages sent from producer to Topic from yesterday. I send few messages from producer now and could see that offset details.

` bin/kafka-consumer-groups.sh --describe --bootstrap-server localhost:9092 --group testgroup2
`
```
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).


TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
test                           0          73              73              0          sarama-784a42e0-e692-48ba-9c53-567e4f230e42       /0:0:0:0:0:0:0:1               sarama
```

Also, I am using consumer.MarkOffset(XX, "").

**Comment by mohigup** [comment]
I see increasing number of Partition to 2 resolved the error 🤔 . It will great if someone could throw some light on this.
