### ISSUE TITLE
EOF error while fetching new messages

### ISSUE THREAD

**Issue by DimaSalakhov** [bsm/sarama-cluster#142]
I've noticed that some of my consumers are failing with EOF errors. I cannot attribute it to a particular kafka cluster state as it happens with different topics at a different time.

Here are the logs immediately before the error happens (they are all logged by sarama):

> {"level":"info","msg":"consumer/broker/1 abandoned subscription to core.v1/10 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.\n","source":"sarama","time":"2017-07-05T19:55:11.559+0000"}
> {"level":"info","msg":"consumer/core.v1/10 finding new broker\n","source":"sarama","time":"2017-07-05T19:55:13.564+0000"}
> {"level":"info","msg":"client/metadata fetching metadata for [core.v1] from broker node5:9092\n","source":"sarama","time":"2017-07-05T19:55:13.564+0000"}
> {"level":"info","msg":"consumer/broker/5 added subscription to core.v1/10\n","source":"sarama","time":"2017-07-05T19:55:13.565+0000"}
> {"level":"info","msg":"consumer/broker/5 disconnecting due to error processing FetchRequest: EOF\n","source":"sarama","time":"2017-07-05T19:55:13.565+0000"}
> {"level":"info","msg":"Closed connection to broker node5:9092\n","source":"sarama","time":"2017-07-05T19:55:13.565+0000"}

After that I'm getting an error on the Errors() channel

> {"level":"error","msg":"Failure in messages consumption: kafka: error while consuming core.v1/10: EOF","time":"2017-07-05T19:55:13.565+0000"}

Consumer configuration:
```
config := cluster.NewConfig()
config.Consumer.Offsets.Initial = sarama.OffsetOldest
config.Consumer.Return.Errors = true
config.Group.Return.Notifications = true
cluster.NewConsumer(brokers, consumerGroup, []string{topic}, config)
```

Kafka version: 0.10.0.1
Libs:
{
	"checksumSHA1": "50/2Bv2EHsoyhrd7ddZKIFMIkoo=",
	"path": "github.com/Shopify/sarama",
	"revision": "c01858abb625b73a3af51d0798e4ad42c8147093",
	"revisionTime": "2017-05-08T18:36:27Z"
},
{
	"checksumSHA1": "umXxyjOWk2aQKrvTqRsYJypuhlw=",
	"path": "github.com/bsm/sarama-cluster",
	"revision": "045a96d0acad1692fa63ca3cfb15c452115516ae",
	"revisionTime": "2017-04-20T12:56:59Z"
}

**Comment by dim** [comment]
It doesn't look like an error that is triggered by sarama-cluster but is
coming from sarama itself.

Looking at it, I would say that your server is closing the client
connection due to a missed heartbeat. You should check your server
configuration and adjust accordingly. You could also raise a ticket with
sarama if that doesn't help.

**Comment by DimaSalakhov** [comment]
That's a good point @dim 
I've missed the fact that there is a `MaxProcessingTime` setting in a consumer config, that might be it. I'll change my processing logic to try it out and if remains try to hold off sarama team.
Thanks!
