### ISSUE TITLE
OffsetStash and out-of-order messages

### ISSUE THREAD

**Issue by dadrian** [bsm/sarama-cluster#143]
I'm a little confused about how to properly use OffsetStash, although I may just have a misunderstanding about Kafka.

Here's my use case: I have a topic of incoming data, consumed by a single goroutine in Golang. This channel parses data off the Kafka topic, and adds it to a second channel, which fans-out to N processors. These processors annotate the data, and then fan-in back to a single goroutine producer, which adds the annotated data to a different Kafka topic. To be crash safe, I don't want to mark any message as consumed until after I have produced the annotated message to the "outgoing" topic.

I was initially going to use an OffsetStash to track ID's as they were produced, and occasionally have the consumer commit them back. However, what I'm not clear about is if this will still result in dropped records on crash.

Consider the following scenario: incoming messages with ID's 1 to 10 come in. Because there are N parallel processors, we get "unlucky" and message 10 is processed first. I add "10" to the OffsetStash and commit latest offset. While messages 1-9 are still processing, the program crashes (and I have not yet added them to the OffsetStash). If I understand OffsetStash correctly, I will have committed an offset of 10, but not yet processed 1-9. Is this correct?

I expect I need to implement some form of my own ID tracking, but I want to make sure this isn't a use case covered by Sarama Cluster before I do.

Thanks, and apologies in advance if I'm totally off base here!

**Comment by dim** [comment]
Hey, not totally off-base, no, but this is how Kafka works in general. You "ack" messages (topic/partition/offset) that you have processed with the latest offset being committed. OffsetStash is meant to simplify bulk processing, when you process messages (from multiple partitions) in batches, e.g. you accumulate N messages and stash their offsets, then you update your DB and commit the whole offset batch to Kafka in one go.

Given your use-case, it seems more appropriate to "fan-out" through Kafka + sarama-cluster itself. Increase the number of partitions of your topic to N  and start M parallel sarama-cluster consumers (either in multiple go-routines or even separate, distributed processes). Sarama-cluster will automatically divide the partitions among your consumers (each consumer subscribes to N/M partitions). As the messages from the partitions will arrive in sequential offset order, there is no need implement your own ID tracking.

Hope that helps!

**Comment by dadrian** [comment]
Thanks!
