### ISSUE TITLE
Recommendation for creation new subscribers

### ISSUE THREAD

**Issue by chandradeepak** [bsm/sarama-cluster#144]
what is the recommended way of creating new subscribers.  Is sarama.NewConsumerFromClient or sarama.NewConsumer is better ?

Assuming we have a node which connects to kafka cluster(say  5 node)  is it better to maintain a pool of sarama connections for both publishers and subscribers and reuse them for both pub and sub. or create new connection to kafka for each pub and sub client . if it is better to limit the number of connections from a node to kafka cluster what is the limit . 

Any suggestions ?

**Comment by dim** [comment]
All producers/consumers within the same process can use the same client but - in special circumstances - it may have a negative impact on performance. Sorry, this is actually not quite sarama-cluster specific, but there is a nice explanation in the sarama documentation - http://godoc.org/github.com/Shopify/sarama#Client
