### ISSUE TITLE
Consume on one specific partition

### ISSUE THREAD

**Issue by thanhpk** [bsm/sarama-cluster#146]
Hi, my topic have multiple partitions, is there any chance that I can create a consumer which listen on exactly 1 specified partition instead of all partitions?
thanks,

**Comment by dim** [comment]
Sarama cluster will always divide your partitions by the number of available consumers. If you start as many consumers as partitions, each consumer will consume one partition, but there is no guarantees for "exactly one". If you want to consume *exactly one* partition with your consumer, you need to use http://godoc.org/github.com/Shopify/sarama#Consumer directly.

**Comment by thanhpk** [comment]
one consumer might listen on multiple partitions but sarama cluster ensures that one partition can only be listened by at most one consumer at a time right?
thanks,

**Comment by dim** [comment]
correct! :)
