### ISSUE TITLE
how to retry consum msg?

### ISSUE THREAD

**Issue by neoduan** [bsm/sarama-cluster#149]
when my worker consum, got msg1, msg2 and msg3. there is an error when handle msg2, so i did not call MarkOffset, and i want to retry get msg2, what should i do?

**Comment by dim** [comment]
@neoduan that's technically up to you :)

1. if you can't miss a message, why don't you simply add a retry on errors and retry indefinitely until it succeeds or the process terminates
2. you could close and re-open your consumer, which would trigger a rebalance of the cluster
