### ISSUE TITLE
Delay in starting to consume from fresh topic

### ISSUE THREAD

**Issue by JeanMertz** [bsm/sarama-cluster#153]
We've got a test-suite that runs against a live (local) Kafka cluster to test our implementation. Things are working as expected, except for a variable delay in the actual messages starting to be consumed from a topic that is freshly created for each test-run, and has messages present (validated using `kafkacat`).

Here are two different logs, one working as expected, instantly consuming the messages:

```
2017/08/16 11:43:25 cluster/consumer  rebalance
2017/08/16 11:43:25 client/metadata fetching metadata for all topics from broker localhost:9092
2017/08/16 11:43:25 client/coordinator requesting coordinator for consumergroup test-group from localhost:9092
2017/08/16 11:43:25 client/coordinator coordinator for consumergroup test-group is #0 (192.168.1.52:9092)
2017/08/16 11:43:25 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2017/08/16 11:43:25 Connected to broker at 192.168.1.52:9092 (registered as #0)
2017/08/16 11:43:25 cluster/consumer sarama-63005d82-8f20-4cf1-8ce9-97b84efba024 consume input/0 from -2
2017/08/16 11:43:25 consumer/broker/0 added subscription to input/0
```

And a second one, where you can see a delay of 20 seconds before the actual consumption of messages starts. This is using a clean-slate, new topic and no existing consumer groups:

```
2017/08/16 11:43:36 cluster/consumer  rebalance
2017/08/16 11:43:36 client/metadata fetching metadata for all topics from broker localhost:9092
2017/08/16 11:43:36 client/coordinator requesting coordinator for consumergroup test-group from localhost:9092
2017/08/16 11:43:36 client/coordinator coordinator for consumergroup test-group is #0 (192.168.1.52:9092)
2017/08/16 11:43:36 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2017/08/16 11:43:36 Connected to broker at 192.168.1.52:9092 (registered as #0)
2017/08/16 11:43:55 cluster/consumer sarama-7ceaf489-5e23-4f9f-b6f5-65e119816197 consume input/0 from -2
2017/08/16 11:43:55 consumer/broker/0 added subscription to input/0
```

The "cluster/consumer x consume y" line happens [at the start of `Consumer.createConsumer`](https://github.com/bsm/sarama-cluster/blob/0e986befc20e6883c4e91bb95129829cdbe53a42/consumer.go#L732-L733), which [is called in `Consumer. subscribe`](https://github.com/bsm/sarama-cluster/blob/0e986befc20e6883c4e91bb95129829cdbe53a42/consumer.go#L510), but logging is kind of sparse inside that function, so I'm not sure where the exact bottleneck could be.

Do you have any insights in this? Or is there a configuration setting we can use during testing to get rid of this random delay?

**Comment by JeanMertz** [comment]
By the way, so far I've only encountered delays of exactly 15 or 20 seconds, so it could be some retry logic?

**Comment by JeanMertz** [comment]
In fact, it looks like the individual test cases weren't properly closing the consumers. I'm not sure how or why, but this resulted in new consumers being delayed before processing messages.

I don't know the exact semantics, because the topics (and consumer groups) to which the consumers are subscribed are scrubbed after each test, but after adding the proper logic to close the consumers after each test, the delays no longer occurred, and the testing times have been very stable.

**Comment by dim** [comment]
> I'm not sure how or why, but this resulted in new consumers being delayed before processing messages ...

That's easy to explain. The Kafka server maintains a heartbeat timeout after which a rebalance is triggered. Equally, if you try to join cluster with a new consumer, it will wait for N seconds until it has received a ping from all current consumers. If not hearbeat is received, it will mark the current generation as dead and only then accept the new consumer.
