### ISSUE TITLE
Can two different consumer groups maintain and mark different offsets for the same topic?

### ISSUE THREAD

**Issue by joelpresence** [bsm/sarama-cluster#154]
Hi,

I tried digging around in the code, but I can't see for sure: could two different consumer groups like `group1` and `group2` both mark different offsets for the same topic and partition?

For example, suppose that I have a topic `topic1` and I want two different consumer groups:

* `metrics` records metrics the topic to Redis
* `archive` logs messages to S3

So suppose the `metrics` consumer group consumes messages twice as fast as the `archive` consumer group does.  Will that be a problem?  Could `metrics` mark its offset in partition 3 of the topic as 400 but group `archive` mark its offset in that same partition as only 200?

It looked like your mark offsets was marking offsets by topic and partition only, I couldn't see where the consumer group name was used in marking offsets.

Thanks!

**Comment by dim** [comment]
No, the scenario you have described works and it's what Kafka was originally intended for. Each consumer is initialised with its own `groupID`, see [here](https://github.com/bsm/sarama-cluster/blob/dd314eb760dff6c472b5fac7b97b0c66fc622d51/consumer.go#L69). When offsets are committed, they are always committed for a particular `group/topic/partition` combination, see [here](https://github.com/bsm/sarama-cluster/blob/dd314eb760dff6c472b5fac7b97b0c66fc622d51/consumer.go#L146).


The MarkOffsets marks the offset for a
