### ISSUE TITLE
Any reason for 30 second delay before receiving data

### ISSUE THREAD

**Issue by kchaliki** [bsm/sarama-cluster#156]
Hello, we are trying to find the reason for what is a suspiciously precise 30 second wait between calling cluster.Consumer.Messages() and receiving the first data. Data arrived very fast after that. Could this be a setting in sarama-cluster or should we look at our kafka configuration?

**Comment by dim** [comment]
Did you see https://github.com/bsm/sarama-cluster/issues/153?

**Comment by kchaliki** [comment]
Thank you - my search for '30' wasn't very useful here...
