### ISSUE TITLE
sarama clients leak memory if there are lot of topics

### ISSUE THREAD

**Issue by chandradeepak** [bsm/sarama-cluster#158]
with regards to the issue of leaking memory in metadata updation this is fixed in based sarama code. but sarama-cluster calls Refreshmetadata directly which would git the condition of getting all topics desipte that sarama.client is not used for those topics . this would help us keep tabs on the memory in check . Shopify/sarama#931

i submitted a pull request with the fix which is tested. 

the pull request tests failed because travis didn't pick the latest sarama .

**Comment by dim** [comment]
Continuing in #159
