### ISSUE TITLE
Partition offsets out of range fails rebalancing

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#16]
I've found that if my client hasn't run in a while and the partition index in ZK falls outside the valid range for Kafka, I get an error.  This was fixed, but I think changes to Shopify/sarama have broken this.  It looks like when you call consumer.ConsumePartition, the index is checked, fails, and an error is returned from the claim function.  However, the Zookeeper node for the partition has by then been claimed, so when sarama-cluster tries to adjust the index and try again, the node is already claimed, fails, and falls into a loop.

**Comment by sbowman** [comment]
Here's my quick fix...a bit messy, but it seems to handle the problem (consumer.go)

```go
func (c *Consumer) claim(tp topicPartition) (sarama.PartitionConsumer, error) {
        // ... 
	var consumer sarama.PartitionConsumer
	for consumer == nil {
		consumer, err = c.consumer.ConsumePartition(tp.topic, tp.partition, offset)
		if err != nil {
			if err == sarama.ErrOffsetOutOfRange {
				offset, err = c.client.GetOffset(tp.topic, tp.partition, sarama.OffsetOldest)
				if err == nil {
					c.rLock.Lock()
					c.read[tp] = offset
					c.rLock.Unlock()
				}
			} else {
				return nil, err
			}
		}
	}
	return consumer, nil
}
```

**Comment by dim** [comment]
sarama-cluster.v1 is now deprecated in favour of v2
