### ISSUE TITLE
Unnecessary wait before fetching offsets

### ISSUE THREAD

**Issue by vavrusa** [bsm/sarama-cluster#161]
I think there's another issue that surfaces when the DwellTime is longer to allow for long consumer processing. So the process of rebalance is as follows:

1. release subscriptions
2. wait for DwellTime
3. commit offsets
4. re-join consumer group
5. restart heartbeat
6. subscribe to partitions

This code runs last, in the step 6, so it means the rebalance is done and all members either rejoined the group within DwellTime or Session.Timeout has passed and unresponsive hosts are excluded, but either way the coordinator has already issued assignments, so the consumer can start whenever instead of waiting for an extra 2*DwellTime here:

https://github.com/bsm/sarama-cluster/blob/96ddfcd36f56f11fc80ff0d466128c1825ace08a/consumer.go#L672-L682

It's not an issue in streaming case because 2*DwellTime is a few hundred milliseconds, but if the DwellTime is a few seconds it, the double can exceed the Session.Timeout and consumer loses the assignment before it can even start.

**Comment by dim** [comment]
@vavrusa addressed in #168
