### ISSUE TITLE
Automagically commited offset in case of a crash

### ISSUE THREAD

**Issue by niels-s** [bsm/sarama-cluster#164]
We got an issue when our process crashes we found out that the offset for our consumer group is automagically committed without we did it explicitly. So I'm wondering if we are missing a particular setting that could indicate why this is happening?
We want to fail hard asap and the offset shouldn't be committed so we can retry once we start the process again or after we fixed the issue for example.

We are using latest version of [Sarama 1517403](https://github.com/Shopify/sarama/commit/15174039fd207656a0f97f52bc78ec7793deeada) and [sarama-cluster 96ddfcd](https://github.com/bsm/sarama-cluster/commit/96ddfcd36f56f11fc80ff0d466128c1825ace08a).
But I only updated to the latest version to see if this wasn't a bug already fix, we previously used [Sarama 3efb95d](https://github.com/Shopify/sarama/commit/3efb95dad8fbcd194d3c06f7b9c40eabeb719b36) and [sarama-cluster 5d8c110](https://github.com/bsm/sarama-cluster/commit/5d8c11085c875b3155870da9ba6be706429a95dc) 
Also using different versions of Golang 1.8 and 1.9

Probably I'm overlooking something obvious like always but I'm almost 100% I've tested this case a while back and it worked fine back then. So perhaps it's a regression some where 🤔 

ps: kuddo's for this awesome library we use it a lot ;) 

```go
package main

import (
	"log"

	"github.com/Shopify/sarama"
	"github.com/bsm/sarama-cluster"
)

func main() {
    consumer := createConsumer()
    for m := range consumer.Messages() {
        log.Printf("Got a message")
        panic("bla")
	consumer.MarkOffset(m, "")
    }
}

func createConsumer() *cluster.Consumer {
	config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true
	config.Version = sarama.V0_10_0_1

	broker, topic, consumerGroup := "localhost:9092", "p-bundles", "crash-test"

	consumer, err := cluster.NewConsumer([]string{broker}, consumerGroup, []string{topic}, config)
	if err != nil {
		panic("Failed to start kafka consumer: " + err.Error())
	}

	return consumer
}

```

**Comment by dim** [comment]
@niels-s offsets marked via `MarkOffset` will be committed on:

1. `Close()`
2. on internal rebalance
3. based on this setting, which defaults to 1s - https://github.com/Shopify/sarama/blob/3efb95dad8fbcd194d3c06f7b9c40eabeb719b36/config.go#L210

Hope that explains it

**Comment by niels-s** [comment]
@dim sorry but this doesn't explain it to me, the panic will cause we will never reach the `MarkOffset` statement, so why is the offset committed then? 

The message (offset) should never me marked as consumed, so could you elaborate a little more what a reason could be the offset is marked and committed anyway?

**Comment by dim** [comment]
@niels-s sorry, missed the panics. 

To elaborate, offsets are exclusively committed through `consumer.CommitOffsets(...)` - see [here](https://github.com/bsm/sarama-cluster/blob/bf90d49977432bc4e8f263d754bdc2a33b4beed8/consumer.go#L174). `CommitOffsets` can  either be called manually or through the [commit loop](https://github.com/bsm/sarama-cluster/blob/bf90d49977432bc4e8f263d754bdc2a33b4beed8/consumer.go#L371) or on [rebalance/close](https://github.com/bsm/sarama-cluster/blob/bf90d49977432bc4e8f263d754bdc2a33b4beed8/consumer.go#L433).

Unfortunately, I cannot explain it from the snippet you mentioned above. Offsets are only committed to Kafka if the topic/partition is marked as "dirty" and that only happens when the the offset has been updated locally through `MarkOffset`

**Comment by dim** [comment]
Here's a test I just added - https://github.com/bsm/sarama-cluster/commit/3a8591c00548b67617971bb9df75f7745057a7c4#diff-e85d03976d9766c4d00ac176511d4f06R191

**Comment by chen56** [comment]
v2.1.8 has this bug.
master has fixed this bug.
need publish new version.

**Comment by dim** [comment]
@chen56 I will prep a new release later this week. thanks

**Comment by carl-leopard** [comment]
so offset will not be committed without calling `MarkOffset`?

**Comment by dim** [comment]
@carl-leopard sorry this library is deprecated, but how should the consumer know what to commit if you don't mark the messages as 'processed'

**Comment by carl-leopard** [comment]
soga
