### ISSUE TITLE
Consumer can not set arbitrary offset

### ISSUE THREAD

**Issue by warreneblackwell** [bsm/sarama-cluster#165]
https://github.com/bsm/sarama-cluster/blob/5efe630369ab4ed5cc4cedeadd61b4d1b2523169/config.go#L118

Is there a particular reason consumers can not set offsets other than sarama.OffsetOldest, sarama.OffsetNewest? Consumers which would like to consume other (in range) offsets cannot do so given this check.

**Comment by dim** [comment]
@warreneblackwell good question but the answer is simple. sarama-cluster is all about consuming a topic in a cluster hence it uses kafka offset management to determine the exact offset to start/resume from. the OffsetOldest/OffsetNewest config option is a fallback option, in case there is no stored offset or it's too old and has been expired by the server. if you want to resume a topic/partition from a specific offset, you must commit it to the kafka offset storage

**Comment by mymixing** [comment]
@dim how can I operate, pointing to a specific offset, thank you
