### ISSUE TITLE
Deadlock when sarama commit an out of range offset

### ISSUE THREAD

**Issue by aravindvs** [bsm/sarama-cluster#167]
This is a dup of: https://github.com/bsm/sarama-cluster/issues/121

Reopening this with data here: 
`
I am reopening this one as I saw a similar behavior:
(1) Producer was producing at a much higher rate than the consumer
(2) Consumer was trying to commit offset which is already deleted.

I was able to log the error message as well by listening on consumer.Errors() channel and got this one:
kafka-consumer : Failed to consume message. Error: kafka: error while consuming topic: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
After this since the pc.Loop() above doesn't refresh, which means we will just be stuck as @plopik mentioned above. I think it will be better to just trigger a rebalance() which should get us out of this situation as mentioned earlier.
`

**Comment by dim** [comment]
@aravindvs can you please test with https://github.com/bsm/sarama-cluster/pull/169, this should fix you issue once and for all

**Comment by aravindvs** [comment]
@dim - Thanks! will definitely try it and let you know.

**Comment by dim** [comment]
Should be fixed, please re-open if you still experience problems
