### ISSUE TITLE
Incremental consumer subscriptions to topics

### ISSUE THREAD

**Issue by agforte** [bsm/sarama-cluster#170]
Hi all, I was wondering if there are plans to support a way for a consumer to subscribe to new topics as new subscribe requests come in. That is, adding new topics to current ones. Currently, the only way I can see of doing it is by creating a new consumer group every time a new subscription request comes in, and load as topics the topics of the old group plus the new topic. This, however, seems to be very inefficient.

Thanks.

**Comment by dim** [comment]
The consumer group configuration supports subscription via `config.Group.Topics.Whitelist` and `config.Group.Topics.Blacklist`, please see https://godoc.org/github.com/bsm/sarama-cluster#Config, jope that helps

**Comment by agforte** [comment]
Thank you for your answer. Unfortunately, Whitelist and Blacklist do not work. You set them up in the Config but then a sarama.Client is started with that config and the sarama.Client does not support Whitelist and Blacklist.

In particular, your function:
```
func NewClient(addrs []string, config *Config) (*Client, error) {
```
calls:
```
	client, err := sarama.NewClient(addrs, &config.Config)
```
which does not do anything with Blacklist and Whitelist (I had opened an issue with Sarama). Unless I have missed something, currently Whitelist and Blacklist do not have any effect on the Consumer.

**Comment by dim** [comment]
You need to do that on cluster.Config, not sarama.Config, please see the
link I posted earlier

**Comment by agforte** [comment]
Perhaps, I was not clear. I did see your link, but the cluster.Config is not used by anyone except for the sarama.NewClient which ignores Whitelist and Blacklist. 
I also wrote a test program to confirm this. I set two regex, one in Whitelist and one in Blacklist of cluster.Config and found out that both are ignored by the cluster.NewConsumer which is not surprising since the cluster.NewConsumer is just a sarama.NewClient which ignores the two lists.

**Comment by dim** [comment]
Hey again, sorry, now I see the issue. You need to pass the config to
`cluster.NewConsumer`

**Comment by agforte** [comment]
Indeed. I do pass it to cluster.NewConsumer() but if you look at the implementation of cluster.NewConsumer(), you will see that it is calling cluster.NewClient() which is calling sarama.NewClient() which does not support Whitelist and Blacklist. So, in the code you have:
`cluster.NewConsumer() --> cluster.NewClient() --> sarama.NewClient()`

Please see here:
https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/consumer.go#L70

https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/client.go#L22

**Comment by dim** [comment]
So it is used by the consumer itself. It has a background check to identify new topics in:
https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/consumer.go#L333

It is then using the white/blacklists here:
https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/consumer.go#L764

**Comment by agforte** [comment]
Thanks that makes sense. However, in the code you point to, the Blacklist and Whitelist are just checked against in order to decide if an *existing* extra topic should be added or not when a rebalancing occurs. Where this extra topic comes from seems to be a mystery. My initial post to this thread was asking how to add this extra topic. I proposed a possible way but that seems very inefficient. What is the right way? How do I add an extra topic to an existing cluster.Consumer?

**Comment by dim** [comment]
@agforte sorry, I don't think I don't fully understand your question. Are you asking how to add topics to Kafka? In that case I can only refer you to the Kafka documentation - http://kafka.apache.org/documentation/#basic_ops_add_topic.

As mentioned before, a cluster consumer is periodically scanning Kafka for new topics. If you specify a whilelist, your newly created topic will be picked up by the consumer. Alternatively, if you prefer to configure your consumable topics explicitly, you could just stop your consumers, change your configuration and restart then again. If you do this process one consumer at a time it will not incur any downtime.

**Comment by agforte** [comment]
Thanks for your reply. So, if I understand what you are saying, there is no way to add a topic to Kafka/consumer by using sarama-cluster without stopping consumers? 
In other words, if I have consumers running and I want to add a new topic to the existing consumers using sarama-cluster, I have to stop the consumers and restart them? No other way?

**Comment by dim** [comment]
Well, there is, you could just use a whitelist.

Of course I could add an additional `SubscribeToTopic(topic string)` method
to the API but all it would do is stop the process and restart it with the
new topic included. The problem with this solution though is that it would
be misleading. You would have to run it on each consumer instance
separately. Optionally, it's far easier to stop the consumers, change the
configuration and restart then again. With tools like
https://github.com/hashicorp/envconsul this can be done without any notable
downtime.

**Comment by agforte** [comment]
Could you give me an example of how a topic would be added using the whitelist? I have tried specifying a regex in the whitelist thinking that a producer packet with a topic matching the whitelist would be added by the consumer when receiving it. This however, does not seem to be the case.

**Comment by dim** [comment]
Here you go, just added an example for godoc: https://github.com/bsm/sarama-cluster/commit/08f4fae4d005d9b5867709973471810bcd30b09e

There is also a test for it here:
https://github.com/bsm/sarama-cluster/blob/08f4fae4d005d9b5867709973471810bcd30b09e/consumer_test.go#L127

Please note that, when adding new topics, it may take up to `Config.Metadata.RefreshFrequency` for the consumer to register those

**Comment by agforte** [comment]
Thanks a lot. This works! Is there a penalty to choose a short RefreshFrequency?

**Comment by dim** [comment]
Not sure, I doubt it will have a major impact on performance, but it surely
depends on the number of brokers, clients and the volume of topics. Sorry,
I don't have much in-depth knowledge to give you a fully qualified answer.

**Comment by Preylien** [comment]
I seem to be running into the same issue as what agforte was experiencing above.
I have a consumer with whitelist "test.*"
I have a topic test1 with data in it
I read from test1 and it works fine
I create a separate producer that writes to a new topic, test2 (which is being created by that producer)
I wait for the Config.Metadata.RefreshFrequency interval and it doesn't start reading from test2, but it continues to read from test1

You mentioned the code here:
https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/consumer.go#L333

Looking at it, even if it identifies that a new potential topic exists, this if returns and therefore exits the loop and doesn't do anything with this new topic.
So as far as I can tell it doesn't actually subscribe to the new topics if it finds any. 

Am I misunderstanding this code or is this the wrong place to look for it?

**Comment by dim** [comment]
@Preylien I would appreciate a pull request as I am currently working on the implementation of a `ConsumerGroup` directly into sarama: https://github.com/Shopify/sarama/pull/1099
