### ISSUE TITLE
what should we do if we encounter error while consuming in Errors Channel (EOF)

### ISSUE THREAD

**Issue by chandradeepak** [bsm/sarama-cluster#171]
I had sarama cluster set up as specified in the README.  we had errors enabled and we are listening for them . 

so if consumer.Errors() returns "kafka: error while consuming topicname/4: EOF" are we supposed to close the consumer and start it again. Does that makes sense ?

In cases where we ignored the messages such as above we are have seen that  entire subscription goes in to a limbo state . No messages are received for that particular consumer until restarted. 

I have seen that this issue is discussed here (https://github.com/Shopify/sarama/issues/913)  where you mentioned you return what ever sarama returns but losing connection with one broker does sarama cluster automatically redial the connection or no ?  So in general is it a good idea to restart subscription when there are errors in Error channel  ?

previously i was under the impression that error happening in Error channel would be automatically recovered since any connection loss would be redialed and sarama cluster would recover from it . But i think in case where partition consumer of sarama gets an EOF ( which happens on conn.Read ) we wont automatically recover from those failures.

please suggest what is the right approach .
 

example code given in Readme
for {
		select {
		case msg, more := <-consumer.Messages():
			if more {
				fmt.Fprintf(os.Stdout, "%s/%d/%d\t%s\t%s\n", msg.Topic, msg.Partition, msg.Offset, msg.Key, msg.Value)
				consumer.MarkOffset(msg, "")	// mark message as processed
			}
		case err, more := <-consumer.Errors():
			if more {
				log.Printf("Error: %s\n", err.Error())
			}
		case ntf, more := <-consumer.Notifications():
			if more {
				log.Printf("Rebalanced: %+v\n", ntf)
			}
		case <-signals:
			return
		}
	}

**Comment by dim** [comment]
@chandradeepak this PR should have fixed the problem - https://github.com/bsm/sarama-cluster/pull/169. Could you pls try it and re-open in case it's still an issue

**Comment by chandradeepak** [comment]
Thanks for the PR @dim  but what should we do to encounter or create the errors.  This happened once and i coulnt manually reproduce it .

**Comment by dim** [comment]
> but what should we do to encounter or create the errors...
I don't quite understand what you mean by that, sorry

in general: `EOF` errors are not something that sarama or sarama-cluster can do much about, they are due to network disconnects between your clients and your kafka server. the change that #169 makes is that it forces a rebalance when these errors occur.

**Comment by dongshimou** [comment]
again. 
sarama-cluster version : 704b0be
