### ISSUE TITLE
Migrating offsets from zookeeper to kakfa

### ISSUE THREAD

**Issue by sagard** [bsm/sarama-cluster#175]
I have to upgrade sarama clients from 0.8 to latest version and started using sarama-cluster instead of wvanbergen/kafka. I see that offset will be committed to kafka now.

On Apache Kafka page it says that for doing migration from zk based storage to kafka you need to do following:
Set offsets.storage=kafka and dual.commit.enabled=true in your consumer config.

But wvanbergen/kafka doesn't support these properties and they don't indent to support it.
How can we migrate offsets from zk to kafka? Is default value of dual.commit.enabled true?

Also when i run the following i don't see my groups:
kafka-consumer-groups --bootstrap-server {ip} --list

but i see my groups if i do:
kafka-consumer-groups --zookeeper {ip} --list

Is this expected?

**Comment by dim** [comment]
@sagard sorry for the delay, I am not sure about the correct way for doing this migration as I have never done one myself. `dual.commit.enabled=true` is only supported by the Java client, so it's not something that wvanbergen/kafka would have built-in. I suggest you try the following:

1. stop your `wvanbergen/kafka` consumers
2. read the offsets from zookeeper with `kafka-consumer-groups.sh`
3. use https://github.com/fgeller/kt to set/update the offsets in the new store
4. start your `bsm/sarama-cluster` consumers
