### ISSUE TITLE
Restarting at offset

### ISSUE THREAD

**Issue by nbcohen** [bsm/sarama-cluster#177]
I have written a couple of programs in Go to read data from Kafka topics using the sarama library. Just modified one of those programs to use your cluster library and stream the data instead of managing the partitions individually.

However, if my program stops (or dies, as it is doing in testing), when it restarts, it starts at the current offset of the kafka topic, not where it left off when it died. I don't want to go back to the beginning and reprocess the entire topic, but starting at the end leaves gaps.

In my old program, I periodically wrote the offsets for each partition into a file and set those values on a restart - this forced a bit of reprocessing, but not too much. I only see options to start at the newest or oldest offset in your library - am I missing an option, or is there another way to pick up roughly where I left off when my program was terminated?

Please note that I'm relatively new to Go programming, so I may well have missed something in going through your code...

thanks,

nbc

**Comment by dolzenko** [comment]
Are you sure you're calling https://godoc.org/github.com/bsm/sarama-cluster#Consumer.MarkOffset in your program?

**Comment by nbcohen** [comment]
Actually, I'm sure that I'm NOT calling that routine :) But that may be what I'm looking for - let me go through that part of the documentation and see about modifying my code to do that. That may solve my problem - thanks very much!

nbc

**Comment by nbcohen** [comment]
And that did solve my problem - thanks very much for the help!

nbc

**Comment by dim** [comment]
Thanks @dolzenko
