### ISSUE TITLE
Authentication/Authorization in Kafka

### ISSUE THREAD

**Issue by nbcohen** [bsm/sarama-cluster#178]
I was told yesterday that we will be upgrading (probably Q1 or Q2 or 2018) to a new version of Kafka that will allow for authentication and authorization, so as to prevent random users from accessing or writing indiscriminately to kafka topics. I have not looked into this in detail yet, but I was told that the Confluence Java libraries will be supporting this API change. Can you tell me if your libraries will be implementing these changes as well? I recently started migrating away from Java to Go for much of my Kafka related activities - I'd rather not go back if I don't have to, but of course I will if necessary...

Thanks

nbc

**Comment by dim** [comment]
@nbcohen sarama-cluster is a wrapper around sarama, which supports authentication, see the documentation here - https://godoc.org/github.com/Shopify/sarama#Config. Please be aware that sarama doesn't have support for Kafka v0.11 yet - https://github.com/Shopify/sarama/issues/901
