### ISSUE TITLE
ConsumerRebalanceListener alternative

### ISSUE THREAD

**Issue by wannes-ds** [bsm/sarama-cluster#18]
Similar to the [ConsumerRebalanceListener](http://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html) of the Java API, it would be great to get informed by the consumer that the partition assignments have changed so related state can be updated or logged.

On first glance, adding a channel to the API where rebalance events are posted and selected in the same loop as Messages seems like a good idea.
Removals would get posted before https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L267, whereas additions would get posted after the partition consumer was succesfully created, following the specifications outlined in the Java doc.

**Comment by dim** [comment]
Superseded by #21
