### ISSUE TITLE
Safe in-order offset commit to partition with multiple consumer threads

### ISSUE THREAD

**Issue by jescochu** [bsm/sarama-cluster#186]
I have a use case where it is possible that a consumer reading messages from a partition could get tied up with processing the message for possibly minutes at a time. This would lead to messages backing up on the partition that this consumer is reading from.

What I would like to have happen is to have multiple threads on a single consumer instance so the consumer could continue reading off the partition and processing these long running jobs in parallel (and in the background) without fear of committing the offsets back out of order (since I can't know which jobs will finish processing first).

In the "Offset Management" section of [this article](https://engineering.siftscience.com/concurrency-and-at-least-once-semantics-with-the-new-kafka-consumer/) it sounds like these guys wrote a lib that enforced that only the newest offset with all preceding offsets that have been 'marked' as processed would be committed. Is there any plan to have something similar for sarama-cluster eventually? If this were added in via a configuration option, would be this something in scope for this project?

**Comment by dim** [comment]
@jescochu that is already built in into sarama-cluster which will only accept an offset if it's larger than a previously marked one, see https://github.com/bsm/sarama-cluster/blob/master/partitions.go#L177 and also https://github.com/bsm/sarama-cluster/blob/master/offsets.go#L32
