### ISSUE TITLE
Version lock in 2.1.9 for sarama

### ISSUE THREAD

**Issue by frankdejonge** [bsm/sarama-cluster#190]
In the latest release (2.1.9) the sarama version is locked to a specific hash which prevents the sarama dep from being updated. There doesn't seem to be a specific reason for this. The proposed solution would be to revert back to the semver contraint.

**Comment by dim** [comment]
Damn, sorry, fixed! Released v2.1.10

**Comment by frankdejonge** [comment]
@dim thanks for the rapid response 👍
