### ISSUE TITLE
Make Close drain partitions, and add AsyncClose

### ISSUE THREAD

**Issue by ooesili** [bsm/sarama-cluster#193]
I've recently started using `Consumer.Partitions()` in my application, and I've
noticed something I perceive as an inconsistency in the design of the API,
specifically how `Close()` interacts with `Partitions()` and `Messages()`.

Since `Consumer.Close()` takes responsibility of draining the messages and
errors channels, I must tell my own code to stop reading from those channels
before I call close the consumer. Otherwise, I will be competing with the close
process for messages and errors.

This conflicts with the model of how the partitions channel must be handled.
With `Consumer.Partitions()`, I am fully responsible for draining that channel.
This does require a little extra ceremony to get a clean shutdown. Here is a
simplified version of the code in our app.
```go
// some other goroutine closes done
func run(consumer cluster.Consumer, done <-chan struct{}) {
  var wg sync.WaitGroup

PartitionLoop:
  for {
    select {
    case partition := <-consumer.Partitions():
      wg.Add(1)
      go func(partition cluster.PartitionConsumer) {
      MessageLoop:
        for {
          select {
          case message, ok := <-partition.Messages():
            // this is needed to handle rebalancing
            if !ok {
              break MessageLoop
            }
            fmt.Println(string(message.Value))
          case <-done:
            break MessageLoop
          }
        }
        wg.Done()
      }(partition)
    case <-done:
      break PartitionLoop
    }
  }
  wg.Wait()

  // I wish Close did this for me
  go func() {
    for range consumer.Partitions() {
      // drain
    }
  }()
  consumer.Close()
}
```

Although it's not super hard to do, it does feel like an inconsistency, and
more work than strictly should be necessary.

On a very related note, here is the original code I had before I realized there
was no `AsyncClose` in cluster. In my opinion this is much simpler to read and
test. (My tests didn't even need to launch any goroutines!)
```go
// some other goroutine calls consumer.AsyncClose
func run(consumer cluster.Consumer) {
  var wg sync.WaitGroup

  for partition := range consumer.Partitions() {
    wg.Add(1)
    go func(partition cluster.PartitionConsumer) {
      for message := range partition.Messages() {
        fmt.Println(string(message.Value))
      }
      wg.Done()
    }(partition)
  }

  wg.Wait()
}
```

The really nice thing about this is that I don't need 2 different ways to stop
reading from a partition consumer. A partition shutting down due to a rebalance
looks the same as a partition shutting down from the consumer being closed.

So, my two asks of this issue are

1. Add `AsyncClose()` to `Consumer` that mirrors sarama's `AsyncClose()`.
2. Have `Consumer.Close()` drain the partitions channel.

I would not mind taking a stab and implementing this, but I'd rather get some input on this idea before I start.

**Comment by dim** [comment]
@ooesili I do agree with "Have Consumer.Close() drain the partitions channel.", I think it's a simple fix to your problem. Could you please submit a PR for it? I would really appreciate some help at the moment. 

I am not such a big fan of `AsyncClose()`, it doesn't really add much to it in this case. You could just call `go c.Close()` and it would do exactly the same thing

**Comment by ooesili** [comment]
It would not do exactly the same thing as `go c.Close()`, because `AsyncClose` would not try to drain the errors or messages channels. The fact that `Close` tries to drain messages and errors means that I cannot use `range` on those channels, as I'd risk losing messages.
