### ISSUE TITLE
Did not rebalance for Apache Kafka 1.0.0

### ISSUE THREAD

**Issue by canyou2014** [bsm/sarama-cluster#194]
I run a consumer group with 3 members for Apache Kafka 1.0.0, but it seams did not rebalance successfully.
```
2017/12/08 11:17:22 Rebalanced: &{Type:rebalance start Claimed:map[] Released:map[] Current:map[]}
2017/12/08 11:17:27 Rebalanced: &{Type:rebalance OK Claimed:map[] Released:map[] Current:map[]}
```
It work well for Apache Kafka 0.9.

**Comment by dim** [comment]
@canyou2014 support for kafka 1.0 is coming soon, see https://github.com/bsm/sarama-cluster/pull/200
