### ISSUE TITLE
Question - creating config and client from existing sarama config and client

### ISSUE THREAD

**Issue by varun06** [bsm/sarama-cluster#202]
Does it make sense to provide convenience function to create cluster config and client from existing sarama config and client? such as 

`func NewClusterConfigFromConfig(cfg *sarama.Config) *Config`

and 

`func NewClientFromSaramaClient(client *sarama.Client, cfg *Config) (*Client, error)`

**Comment by dim** [comment]
@varun06 not sure, no one's asked for it before and I don't really see a use case. you can always do something like:

```
cc := cluster.NewClient(...)
cc.Client = client
```

**Comment by freddiesunarso** [comment]
I have now a use case for this: I have a service acts like both a consumer and producer, and I would like them to share the same config. The producer's config is a `sarama.Config` while the consumer's config is `sarama-cluster.Config`. What's the best way to do this?

**Comment by varun06** [comment]
@freddiesunarso you should just use sarama at this point. I also have same type of service and use sarama. https://godoc.org/github.com/Shopify/sarama#ConsumerGroup
