### ISSUE TITLE
Does sarama-cluster _actually_ supports Kafka 0.11?

### ISSUE THREAD

**Issue by matbhz** [bsm/sarama-cluster#206]
We upgrade our Kafka servers and `server.properties` configs to use Kafka's 0.11 log format and client version.

Upgrading our clients to use Sarama's `sarama.V0_11_0_0` doesn't seem to work, as the client bumps into a "bad" message format (`messageFormat=2`) that is not able to decode, never getting past from this bad offset and consequently lagging multiple partitions.

Using the clients with `sarama.V0_10_2_0`, though, works perfectly in combination with Kafka 0.11 server configs.

**Comment by dim** [comment]
@matbhz did you update sarama too? what version are you using? as you can see the latest release is passing the tests on 0.11 and 1.0, see https://travis-ci.org/bsm/sarama-cluster/builds/318641920

**Comment by dim** [comment]
Oh, I see, I don't set `V0_11_0_0` in my tests either (I believe). It's not a cluster specific issue then, you should raise this with https://github.com/Shopify/sarama

**Comment by matbhz** [comment]
Thanks @dim! Yes, Sarama and all other dependencies were upgraded. I just wanted to make sure I was not facing any more obvious problem. 

We'll stick to `v0_10_2_0` until it's supported by Sarama.
