### ISSUE TITLE
"Version 1" member assignments causing problems

### ISSUE THREAD

**Issue by thomaslee** [bsm/sarama-cluster#211]
Hello,

This code seems to be writing "version 1" member assignments to the consumer offsets topic:

https://github.com/bsm/sarama-cluster/blob/866f63af9fd93a021a90eb6448d49ff27213cbd8/consumer.go#L689-L692

Version 1 doesn't seem to exist in the official clients as of 1.0.0 and/or master:

https://github.com/apache/kafka/blob/14a3d69d9463b2aa26776329610f8fc5eddd0202/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerProtocol.java#L141-L147

Further, it breaks tools like Burrow, which choke on the unknown version number. 😢 

Is there a reason why sarama-cluster is writing version 1 instead of version 0 here? Entirely possible I'm missing something, but as far as I can tell there's no difference between the assignment payload for sarama's "version 1" vs the Java client's "version 0".

**Comment by dim** [comment]
@thomaslee good catch and sorry for the delay. No, there is no particular reason, I probably just looked at the wrong Java code when implementing it. Will fix.

**Comment by dim** [comment]
Sorted in https://github.com/bsm/sarama-cluster/commit/66a68d7f679d6e1d391979e7845c0e5fae06f6c5

**Comment by thomaslee** [comment]
@dim thanks a ton!
