### ISSUE TITLE
Rolling reboot of kafka nodes causing rebalance errors

### ISSUE THREAD

**Issue by jerrygb** [bsm/sarama-cluster#212]
## Problem Description
I am trying to do a rolling reboot of the 4 node kafka cluster doing about 120K messages/s for a specific topic.

Before each reboot, I do ensure that the ISR is complete (based on the replica count) and the leader is properly chosen for all the partitions.

#### Client/Consumer End

However, I keep receiving the following on the sarama logs,

```
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 rebalance error: kafka server: Request was for a consumer group that is not coordinated by this broker.
```

The above message floods the sarama logs. After anywhere between 10-40 minutes, it finally ensures the co-ordinator for group, and also fetches the initial offsets as seen below,

```
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 rebalance error: kafka server: Request was for a consumer group that is not coordinated by this broker.
[sarama]2018/01/18 04:38:29 client/metadata fetching metadata for all topics from broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 cluster/consumer  rebalance
[sarama]2018/01/18 04:38:29 Connected to broker at 10.0.0.1:9092 (registered as #146)
[sarama]2018/01/18 04:38:29 Closed connection to broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 rebalance error: kafka server: Request was for a consumer group that is not coordinated by this broker.
[sarama]2018/01/18 04:38:29 client/metadata fetching metadata for all topics from broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 cluster/consumer  rebalance
[sarama]2018/01/18 04:38:29 Connected to broker at 10.0.0.1:9092 (registered as #146)
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/35 from 44017414845
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/1 from 43977083671
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/19 from 44191339075
```

#### Server End

We co-related this to the group metadata refresh on the **server** at about the same time.

```
{"@timestamp": "2018-01-18T04:24:46.900", "level":"INFO", "thread":"group-metadata-manager-0", "class":"kafka.coordinator.GroupCoordinator", "message":"[GroupCoordinator 146]: Unloading group metadata for test-cg with generation 7617"}
{"@timestamp": "2018-01-18T04:38:29.461", "level":"INFO", "thread":"group-metadata-manager-0", "class":"kafka.coordinator.GroupCoordinator", "message":"[GroupCoordinator 146]: Loading group metadata for test-cg with generation 7617"}
```

Weird part is the generation id remains the same.

Though it looks more to do with kafka, is there any chance anyone knows any setting related to expiry for load/unload of the group metadata cache?

## Configurations

Following configuration options were tried.

#### Client/Consumer End
Metadata Refresh Interval
Offset Reset Maximum
Offset Retention time

#### Server End
auto.leader.rebalance.enable
unclean.leader.election.enable
leader.imbalance.check.interval.seconds
rebalance.max.retries

I tried fiddling with these options, but didnt have much change in results.

## Versions
- **sarama-cluster:** lastest commit
- **sarama:** latest commit
- **kafka:** 2.12-0.10.2.1 and 2.11-0.10.1.1

## Similar problems
https://github.com/Shopify/sarama/issues/846
https://github.com/Shopify/sarama/issues/1004

/copy @dim

**Comment by dim** [comment]
@jerrygb sorry for the delay, but I am not following. Does sarama-cluster eventually stabilise after the servers are rebooted or not? Do the problems start after the first or the last restart?

We are running sarama-cluster with a number of Kafka clusters and things seem to function consistently. The error messages seem to be due to sarama not being able to determine the right topic owner or am I mistaken?

**Comment by jerrygb** [comment]
Hi @dim 

Thank you for the reply.

That is correct. It seems that kafka servers had stale group coordinator data. The fix seems to be that we did safe shutdown of kafka during any rolling upgrades. I tried co-ordinating with the kafka contributor, but they needed a test cluster where it was reproducible, but did not see that happening. We tent to have a fair bit of traffic onto the kafka servers, approximately 100-250k messages/sec.

Thank you for reply again. For now, I think we will stick to the fix of trapping docker SIGTERM and safe shutdown of the kafka process for now.

**Comment by dim** [comment]
I am currently working on the integration of a low level consumer group into sarama, see here: https://github.com/Shopify/sarama/pull/1083. It allows users to write their own, custom consumer implementations. Once accepted, I will work on the higher level cluster consumer, which would be sarama-cluster V3. The rebalance API should then become much simpler and less prone to errors.

**Comment by dim** [comment]
I have drafted a PR of the upcoming V3, please see https://github.com/bsm/sarama-cluster/pull/234
