### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by flybeyond** [bsm/sarama-cluster#213]
After I run go build  when importing "github.com/bsm/sarama-cluster", I get this error 

vendor/github.com/bsm/sarama-cluster/config.go:132:18: c.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)
vendor/github.com/bsm/sarama-cluster/config.go:134:18: c.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)
vendor/github.com/bsm/sarama-cluster/consumer.go:881:29: c.client.config.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)

**Comment by dim** [comment]
Looks like you are using an old version of sarama, see https://github.com/Shopify/sarama/blame/master/config.go#L80
