### ISSUE TITLE
ResetPartitionOffset throws NPE

### ISSUE THREAD

**Issue by georgeteo** [bsm/sarama-cluster#214]
`ResetPartitionOffset` throws NPE if we attempt to reset offsets for a topic-partition that is not in `subs`.  We have a use case that we may attempt to reset offsets for a partition that this consumer may not own (e.g., consider the case of partition rebalance). Seems fairly trivial to make this function noop in this case. I would be happy to submit a PR if this is something that you're open to. 

```
// ResetPartitionOffset marks an offset of the provided topic/partition as processed.
// See ResetOffset for additional explanation.
func (c *Consumer) ResetPartitionOffset(topic string, partition int32, offset int64, metadata string) {
	c.subs.Fetch(topic, partition).ResetOffset(offset+1, metadata)
}
```

**Comment by dim** [comment]
Yes, please, PR would be much appreciated (ideally with a test)

**Comment by georgeteo** [comment]
Thanks. Submitted a PR #215. I'm not super familiar with github because we don't use that internally at my company, so not sure how to assign a reviewer.
