### ISSUE TITLE
Undefined "Full" trait for config metadata

### ISSUE THREAD

**Issue by seeker44** [bsm/sarama-cluster#217]
Apologies in advance if i've missed something obvious, but i received an error when running `go get` for this project, as well as when trying to run it after manually downloading it.

The error is as follows:
`# github.com/bsm/sarama-cluster
../github.com/bsm/sarama-cluster/config.go:132:18: c.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)
../github.com/bsm/sarama-cluster/config.go:134:18: c.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)
../github.com/bsm/sarama-cluster/consumer.go:902:29: c.client.config.Config.Metadata.Full undefined (type struct { Retry struct { Max int; Backoff time.Duration }; RefreshFrequency time.Duration } has no field or method Full)`

Steps to Reproduce (for me):
1.) Download the library using `go get`
2.) Try to compile

**Comment by seeker44** [comment]
Looking at it further it appears this metadata trait was added to the sarama repo itself in August 2017...but after removing and re-installing the shopify library the attribute is still missing.

Not sure where this ticket belongs in this case....I guess one of the two libraries is in an incompatible state with the other?

**Comment by seeker44** [comment]
I did miss something obvious, I hadn't run `go get -u` in a while. Running that for Sarama appears to have fixed my problem :)

**Comment by dim** [comment]
I suggest using https://github.com/golang/dep, which would have picked up that problem - https://github.com/bsm/sarama-cluster/blob/master/Gopkg.toml#L26
