### ISSUE TITLE
support for exactly once delivery feature from kafka 0.11

### ISSUE THREAD

**Issue by honghzzhang** [bsm/sarama-cluster#219]
Is there support for exactly once delivery feature that's part of the kafka 0.11?
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/

**Comment by dim** [comment]
Not intentionally, but I would really appreciate a PR or at least some hints on how this needs to be implemented.

**Comment by dim** [comment]
@honghzzhang I will close this one for now, please re-open a PR
