### ISSUE TITLE
Connect to new topics

### ISSUE THREAD

**Issue by veger** [bsm/sarama-cluster#220]
Using the whitelist/blacklist feature it is possible to connect to new topic on an existing customer, but it takes max 10 minutes (Kafka heartbeat?) to connect to a new topic after changing the white list.

Can we trigger this somehow, so we do not have to wait after changing its value?

Or even better, can we have a SubscribeToTopic()/UnsubscribeFromTopic() function pair?

**Comment by georgeteo** [comment]
+1. I would also like a way of updating my topic list of a running consumer. 

Also, I suggest suggest conforming to the official Java client API by exposing `subscribe(topicList []string)` interface. See https://kafka.apache.org/10/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html.

**Comment by georgeteo** [comment]
@veger: I'm curious how you use the whitelist feature to update the topic list to consume for an existing consumer. Are you defining a regex in your whitelist and relying on it to pick up new topics that way? What did you mean by "connect to a new topic after changing the white list"?

**Comment by veger** [comment]
I wanted to have a single consumer that is able to connect to several topic (depending on users input/command). So when the user sends some command to our APIs, the whitelist regexp gets updated.
But unfortunately it  takes (maximum) 10 minutes for the consumer to connect (i.e. start receiving messages from the new topic) to the new topic. When looking at the logs/code I think it is only when a heartbeat is received and the consumer is rebalanced.

So it is working using the whitelist, but it takes too long to be acceptable for our use-case.

**Comment by dim** [comment]
@veger sorry, but I don't really see how whatever I would add would be different from:

```
csmr := NewConsumerFromClient(client, "my-group", []string{"topic-a", "topic-b"})
// ... consume
if err := csmr.Close(); err != nil {
  return err
}

csmr = NewConsumerFromClient(client, "my-group", []string{"topic-a", "topic-b", "topic-c"})
// ...
```

Adding a `SubscribeToTopic` method would be just syntactic sugar for the code above and would also trigger a rebalance.

**Comment by veger** [comment]
Nice, I never saw the `NewConsumerFromClient()` function! We are using the `NewConsumer()` function only.

Only thing is that the message, error, etc. channels are recreated, so it will break listeners to these channels (they need to swap channel when they are drained somehow...?)

So a `SubscribeToTopic()` function it is not fully syntactic sugar, it makes it easier than your solution, as the channels could be left intact/functioning.

**Comment by dim** [comment]
I am currently working on the integration of a low level consumer group into sarama, see here: https://github.com/Shopify/sarama/pull/1083. It allows users to manually trigger a rebalance as well as dynamic changes to topic subscriptions. Once accepted, I will work on the higher level cluster consumer, which would be sarama-cluster V3.

**Comment by dim** [comment]
I have drafted a PR of the upcoming V3, please see https://github.com/bsm/sarama-cluster/pull/234

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
