### ISSUE TITLE
how can I get exist consumer-group and continue consume?

### ISSUE THREAD

**Issue by davidmgkang** [bsm/sarama-cluster#222]
Hello, Thanks to read it.

In example code, just using `NewConsumer` function and start consume newest.

but I'd like to call exist consumer groupId and continue consume in topic.

Is there any idea for this?

**Comment by georgeteo** [comment]
`NewConsumer(addrs []string, groupID string, topics []string, config *Config) (*Consumer, error)` already accepts a groupID, which you can pass an existing consumer group ID to register as a worker for that consumer group. https://godoc.org/github.com/bsm/sarama-cluster#NewConsumer

**Comment by davidmgkang** [comment]
@georgeteo 
thank you for replying.
but, in my case, it doesn't work...

**Comment by davidmgkang** [comment]
@georgeteo 

why my consumer group's current offset reset to be -1 ?
When using sarama-cluster, `cluster.PartitionConsumer`'s offset was -1

**Comment by dim** [comment]
@davidmgkang sorry, I am not following. Did you check the documentation and examples in https://godoc.org/github.com/bsm/sarama-cluster.
