### ISSUE TITLE
Release new version of sarama-cluster

### ISSUE THREAD

**Issue by georgeteo** [bsm/sarama-cluster#223]
Can you release a new version of sarama-cluster with #215. I would like to pin to a semver version instead of master.

**Comment by georgeteo** [comment]
Bump @dim?

**Comment by davidmgkang** [comment]
@georgeteo 

Hello, I have a question.

In broker, my topic's a topic partition off was 11000 and my consumer group's that partition's offset was 10100. 
and I run my cluster-consumer but nothing consume. 

but when I produce message to the topic's partition, it consume! 
a number of message is 901.
why my consumer-cluster consume seems activate when produce message?

I don't know why it is... please help me.

**Comment by dim** [comment]
@georgeteo I'm back in the office today and will take a look

**Comment by georgeteo** [comment]
@dim: Thanks!
@davidmgkang: when you initialize your config, you need to set `config.Consumer.Offsets.Initial = sarama.OffsetOldest` to consume from the oldest message in retention.

**Comment by davidmgkang** [comment]
@georgeteo 

but it means Consumer will start consuming at offset no 0 ????
I wanna consume offset no.10101 (in my example case)

**Comment by longquanzheng** [comment]
+1

**Comment by dim** [comment]
Done, see https://github.com/bsm/sarama-cluster/releases/tag/v2.1.13
