### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by petitout** [bsm/sarama-cluster#224]
Hi, 
I have a question about the "consumer mode partitions".
I have this kind of code : 

`func main() {

	config := cluster.NewConfig()
	config.Group.Mode = cluster.ConsumerModePartitions
        ....
	consumer, err := cluster.NewConsumer(brokers, "my-consumer-group", topics, config)
        ...
        // consume errors
	go func() {
		for err := range consumer.Errors() {
		    ...
		}
	}()

	// consume notifications
	go func() {
		for ntf := range consumer.Notifications() {
			....
		}
	}()
	// consume partitions
	for {
		part, ok := <-consumer.Partitions()
                ...
	}
}`

And it is working as expected. I'm receiving notifications on the notification channel, errors on the error channel and messages for each partitions (in the respective channels).
However [here](https://github.com/bsm/sarama-cluster/blob/af1a3507945c581561aebca4e18936a2d67bf8ba/config.go#L33), the comment is saying that in the "ConsumerModePartitions" mode, the error channel and notification channel would not work (and in your README "ConsumerModePartitions" mode example you're not using them)

So my question is  :  in the "ConsumerModePartitions" mode, is it correct to expect errors and notifications on their respective channels ? Or do I have to handle errors on the messages channels ?

**Comment by dim** [comment]
Hi, sorry for the delay. The documentation can be found here: https://godoc.org/github.com/bsm/sarama-cluster#Consumer.Partitions. There is an example too, hope that explains it.
