### ISSUE TITLE
how can i get the uncommited

### ISSUE THREAD

**Issue by wshelly** [bsm/sarama-cluster#225]
when i deal with the msg error, I want to receive it again ,but it will receive the next message, and the uncommitted msg will never received, how can i get the uncommitted msg again? 

func main() {
	// init (custom) config, enable errors and notifications
	config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true
	config.Consumer.Offsets.Initial = sarama.OffsetOldest
	// init consumer
	brokers := []string{"127.0.0.1:9092"}
	topics := []string{"test"}
	consumer, err := cluster.NewConsumer(brokers, "sms", topics, config)
	if err != nil {
		panic(err)
	}
	defer consumer.Close()

	// trap SIGINT to trigger a shutdown.
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	// consume errors
	go func() {
		for err := range consumer.Errors() {
			log.Printf("Error: %s\n", err.Error())
		}
	}()

	// consume notifications
	go func() {
		for ntf := range consumer.Notifications() {
			log.Printf("Rebalanced: %+v\n", ntf)
		}
	}()

	// consume messages, watch signals
	for {

		select {
		case msg, ok := <-consumer.Messages():
			if ok {
				fmt.Printf("topic:%s, partition:%d, offset:%d, value:%s\n", msg.Topic, msg.Partition, msg.Offset, string(msg.Value))
				if err := deal_with(msg.Value); err != nil {
					//if deal_with msg error, nothing to do
					continue
				}else {
					consumer.MarkOffset(msg, "")
				}
			}
		case <-signals:
			return
		}
	}
}

**Comment by dim** [comment]
Currently, you would need to stop and restart the consumer. 

I am currently working on the integration of a low level consumer group into sarama, see here: https://github.com/Shopify/sarama/pull/1083. It allows users to write their own, custom consumer implementations. Once accepted, I will work on the higher level cluster consumer, which would be sarama-cluster V3.
