### ISSUE TITLE
Consumer stopped receiving messages after getting network errors from Consumer.Errors() channel

### ISSUE THREAD

**Issue by wingdog** [bsm/sarama-cluster#227]
Consumer stopped receiving messages after getting the following network errors from Consumer.Errors() channel    

`read tcp xxx.xxx.xxx.xxx:59633->xxx.xxx.xxx.xxx:9102: read: connection reset by peer`

I have to restart the process to make it works.  After spot checking the code base I found the follow functions just return without error handling while the mainLoop still running:

```
cmLoop
hbLoop
twLoop
```

Not sure whether they are the causes of the issue.

**Comment by dim** [comment]
Hmm, is this happening in the latest version? I thought that it has been addressed in one of the more recent releases. Can you reproduce it consistently?
