### ISSUE TITLE
Consumer.Close is stuck if process is terminate before Consumer.subscribe can be finished

### ISSUE THREAD

**Issue by wingdog** [bsm/sarama-cluster#228]
Consumer.Close is stuck if process is terminate before Consumer.subscribe can be finished.  I have to manually kill the process or do the following to be able to terminate the process programatically.

```
closed := make(chan bool)
go func() {
	consumer.Close()
	close(closed)
}()

select {
case <-closed:
case <-time.After(10 * time.Second):
	//return after timeout
}
```

**Comment by jessicaxiejw** [comment]
I am not sure if you have the same error, it only happens to me when the `config.Group.Mode` is set to `ConsumerModePartitions`. It seems to stuck at https://github.com/bsm/sarama-cluster/blob/d98592677c0aa08d8aafb882d344fb461682b722/consumer.go#L834

**Comment by dim** [comment]
@jessicaxiejw I am working on effectively a complete rewrite, which I have drafted as a PR recently, please see https://github.com/bsm/sarama-cluster/pull/234

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
