### ISSUE TITLE
JSON RawMesage - Not able to consume the message

### ISSUE THREAD

**Issue by surajkb74** [bsm/sarama-cluster#229]
I've a json output from a RestAPI call and would like to push the output to kafka topic

type Response struct {
	RequestID     string `json:"requestId"`
	Success       bool   `json:"success"`
	NextPageToken string `json:"nextPageToken,omitempty"`
	MoreResult    bool   `json:"moreResult,omitempty"`
	Errors        []struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Result   json.RawMessage `json:"result,omitempty"`
	Warnings []struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"warning,omitempty"`
}

Content of RawMessage
[{349185634 3360489 2018-03-21T18:31:00Z 101 0   0 [{New Stage ID 29} {Old Stage ID -1} {Reason Lead action} {New Stage Non Marketing Generated} {Old Stage None} {Campaign OP-Lifecycle.00-Non Marketing Generated (New from CRM)}]} {3491856823360489 2018-03-21T18:33:04Z 101 0   0 [{New Stage ID 42} {Old Stage ID 29} {Reason Lead action} {New Stage Customer Nurture} {Old Stage Non Marketing Generated} {Campaign OP-Lifecycle.00-Non Marketing Generated (New from CRM)}]} {349194647 3360095 2018-03-21T18:37:59Z 101 0   0 [{New Stage ID 22} {Old Stage ID 29} {Reason Lead action} {New Stage SAL} {Old Stage Non Marketing Generated} {Campaign OP-Lifecycle.04-SAL (Sales Accepted Lead)}]} ]

My code for producer

msg := &sarama.ProducerMessage{
		Topic: "json_activity1",
		Value: sarama.ByteEncoder(Response.Result),
	} 

Message get deliver to topic.

Below is my consumer code... Consumer doesn't consume the message. 

If I hard code the message in above producer code like
sarama.ByteEncoder("[ above message content]"),  consumer is able to consume the message.

What could be the issue? Can you please help

for {
		select {
		case part, ok := <-consumer.Partitions():
			if !ok {
				return
			}

			// start a separate goroutine to consume messages
			go func(pc cluster.PartitionConsumer) {
				for msg := range pc.Messages() {
					fmt.Fprintf(os.Stdout, "%s/%d/%d\t%s\t%s\n", msg.Topic, msg.Partition, msg.Offset, msg.Key, msg.Value)

					if err != nil {
						fmt.Println(err)
					}
					
					consumer.MarkOffset(msg, "") // mark message as processed

				}
			}(part)
		case <-signals:
			return
		}

Thanks

**Comment by surajkb74** [comment]
json.RawMessage was an array of 300 objects...When I reduce the size to 50 consumer started consuming it.
Question: Whether there is any limit setting on the message size?

**Comment by dim** [comment]
Sorry, there is no limit on sarama-cluster side, it only wraps the native sarama consumers. Please check sarama's config options.
