### ISSUE TITLE
How can i consume msg from a specified offset

### ISSUE THREAD

**Issue by nuoyitech** [bsm/sarama-cluster#230]
I want to consume messages from a specified offset recorded last time.
like java api:

consumer.seek(partition, offset)

After NewConsumerFromClient, I call  consumer.ResetPartitionOffset(topic, partition, offset, meta ), but it does't work.

Thanks a lot.

**Comment by dim** [comment]
Hey, currently, you can only start a sarama.OffsetManager and manually pre-commit offsets you want to start consuming from. 

Also, I am currently working on the integration of a low level consumer group into sarama, see here: https://github.com/Shopify/sarama/pull/1083. It will allow users to build their own, custom cluster consumers. A generic, high-level consumer implementation will still be provided in sarama-cluster V3.
