### ISSUE TITLE
implement my own partition.assignment.strategy

### ISSUE THREAD

**Issue by jchenz** [bsm/sarama-cluster#232]
Currently, sarama-cluster supports "roundrobin" and "range" partition assignment strategies. I want to implement my own strategy to assign the partitions to different consumers.  When I perform partition assignment ( currently done in topicInfo), the method we registers to do the partition assignment should be able to access all members'  UserData from saram.ConsumerGroupMemberMetadata.

**Comment by dim** [comment]
I am currently working on the integration of a low level consumer group into sarama, see here: https://github.com/Shopify/sarama/pull/1083. It comes with an abstract BalanceStrategy interface which allows custom implementations. Once accepted, I will work on the higher level cluster consumer, which would be sarama-cluster V3.

**Comment by jchenz** [comment]
thanks for info.

**Comment by dim** [comment]
@jchenz I have pushed a PR with working draft of V3 - see https://github.com/bsm/sarama-cluster/pull/234

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
