### ISSUE TITLE
Data Race when rebalance notifications are enabled and a rebalance error occurs

### ISSUE THREAD

**Issue by sronderos-atlassian** [bsm/sarama-cluster#236]
in consumer's nextTick function:  https://github.com/bsm/sarama-cluster/blob/d98592677c0aa08d8aafb882d344fb461682b722/consumer.go#L332

A notification is conditionally sent to `handleNotification` if the configuration of the client calls for notifications to be returned. That same notification is then passed to rebalanceError wherein it is modified. This is altering a value on a struct that has been passed across a channel to another goroutine (the notification handler).

I believe that the notification should either always be copied before it is sent or be copied in the event of an error. This will ensure that the notification handler receives distinct notifications for the rebalance start and rebalance error notifications.

**Comment by dim** [comment]
@sronderos-atlassian could you provide a PR for this?

**Comment by pmalekn** [comment]
@dim @sronderos-atlassian is there any intent on merging the mentioned change?

I was just bitten by this data race and the patch seems to fix the issue.

**Comment by dim** [comment]
This library is deprecated, but I am happy to merge this change if you can you submit a PR?

**Comment by sronderos-atlassian** [comment]
@pmalekn @dim I'm no longer using this library. Feel free to take over the change that I made above. I don't recall if we ever switched to using the change in a production setting. I'm fairly confident that the change fixes the issue, but I don't have the bandwidth to test it now.

**Comment by pmalekn** [comment]
Created a PR: https://github.com/bsm/sarama-cluster/pull/295, let me know if that works.

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
