### ISSUE TITLE
how to add a topic dynamic

### ISSUE THREAD

**Issue by jiangxl2018** [bsm/sarama-cluster#237]
i can create topic in system running.
i need add the topic into consumer topiclist.
how to do?
thanks!

**Comment by 90wukai** [comment]
+1

**Comment by 90wukai** [comment]
@jiangxl2018 Do you have any answers?

**Comment by dim** [comment]
Topics can be added dynamically via whitelists and blacklists. I am currently working with the shopify team on an update which will support dynamic topic additions - https://github.com/Shopify/sarama/pull/1099
