### ISSUE TITLE
question for ConsumePartition

### ISSUE THREAD

**Issue by adpoint** [bsm/sarama-cluster#244]
i use api ConsumePartition, one consumer A for one partition 0, one consumer B for one partition 1, when i add one partition or one consumer, then when kafka rebalance,  consumer A also for partition 0?

**Comment by dim** [comment]
Partitions are assigned using a configurable balancing strategy. In the next version of sarama, this will be more flexible, see https://github.com/Shopify/sarama/pull/1099
