### ISSUE TITLE
consumer.Partitions not work?

### ISSUE THREAD

**Issue by adpoint** [bsm/sarama-cluster#246]
i run the example,  when i add partition, use command "./kafka-topics.sh --alter --topic test --zookeeper 127.0.0.1:2181 --partitions 8", but i found my program does not run part, ok := <-consumer.Partitions() again, anything am i wrong?

**Comment by ippoippo** [comment]
I can confirm .... 

I'm doing some experimentation and finding it not working....

Ref: https://github.com/ippoippo/sarama-test/commit/3bafac5247e4841c89ec1b2c6b0d6e3cb1e11512
(I'll reference the commit, in case I push further updates to this repo)

I've written a quick/dirty Producer and Consumer. Single topic....

The Work function`https://github.com/ippoippo/sarama-test/commit/3bafac5247e4841c89ec1b2c6b0d6e3cb1e11512#diff-ba2198d196cba3239fa6b4dfa31f7b2fR13` doesn't seem to work when I publish via my Producer...

The Work2 function `https://github.com/ippoippo/sarama-test/commit/3bafac5247e4841c89ec1b2c6b0d6e3cb1e11512#diff-ba2198d196cba3239fa6b4dfa31f7b2fR48` does seem to pickup from my topic/partition when I publish via my Producer....

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
