### ISSUE TITLE
Consumer and Azure Event Hub Kafka preview, can't connect

### ISSUE THREAD

**Issue by AlexandreRzc** [bsm/sarama-cluster#247]
Hi,

Has anyone tried the preview of Kafka + Event hub on Azure ? 

I couldn't connect to the hub, there is an error when the broker try to join the group
resp, err := broker.JoinGroup(req)

Got this error message :
wsarecv: An existing connection had to be closed by the remote host.

**Comment by dim** [comment]
@AlexandreRzc could you try to connect via raw sarama and raise an issue with them? it doesn't look like a sarama-cluster issue but something that is more low-level.
