### ISSUE TITLE
Heartbeat should be started before partition consumer creation

### ISSUE THREAD

**Issue by wannes-ds** [bsm/sarama-cluster#25]
When a topic has a larger number of partitions and/or is present on a remote server, the creation of each consumer per partition (https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L298) might take longer then the max session timeout (30 seconds). This causes a nasty bug where by the time the first heartbeat is sent after having completed the group sync, Kafka already removed the member from the group, causing another rebalance. This loops infinitely unless by some chance the partition consumer creation takes less than the configured session timeout.

While we have solved this by decreasing the amount of partitions on certain topics, and increasing the timeout for others, would it not be better to start the heartbeat before consumer creation? This 'bug' took us a quite some time to figure out what was going on, as it's not apparent from both the consumer or Kafka.

**Comment by dim** [comment]
Good point, but I will have to think about how to fix it.

**Comment by dim** [comment]
I created a PR which is using a staged rebalance approach. Before I merge, would you mind taking a look>

**Comment by dim** [comment]
Merged #27

**Comment by wannes-ds** [comment]
We've tested this thoroughly in production now, issue seems fixed. Thank you!
