### ISSUE TITLE
Question: what's the plan, if any, for sarama.v2?

### ISSUE THREAD

**Issue by davecb** [bsm/sarama-cluster#251]
I'm using http://gopkg.in/Shopify/sarama.v1 in place of  github.com/Shopify/sarama, and I notice there is a .v2.  Will sarama-cluster track v1, or adopt v2 at a later date?

**Comment by dim** [comment]
@davecb sorry, but gopkg is deprecated in favour of https://github.com/golang/dep and https://github.com/golang/go/wiki/vgo. Both sarama and sarama-cluster releases are properly tagged. I suggest switching to using `github.com/Shopify/sarama` imports

**Comment by davecb** [comment]
Will do, many thanks!
