### ISSUE TITLE
ConsumerGroup with Azure EventHub

### ISSUE THREAD

**Issue by kaliazur** [bsm/sarama-cluster#252]
Hi everyone,

Azure EventHub has implemented the Kafka API and I'm trying to use it with this bsm/sarama-cluster library.

First, the basic library Sarama is working just fine, but i need specifically the "cluster" feature, to be able to use consumer groups.

When I start a consumer on a topic, and after I send a message to this same one, with Sarama I can read the message fine, but with this bsm/sarama-cluster library it's not wotking.

Maybe my configuration is not good or maybe I missed something.

Did anyone already achieved to make this work with the Azure EventHub ?

Do you have any idea in what could I make wrong in my code ?

Thank you so much !

( I put my file example in this post, with different secrets and keys )

[main_test.txt](https://github.com/bsm/sarama-cluster/files/2231261/main_test.txt)

**Comment by dim** [comment]
@kaliazur thanks for the report, I am currently working on an implementation of Consumer Groups into the core library, see https://github.com/Shopify/sarama/pull/1099. I would be very interested in seeing this working with the Azure EventHub, the PR should be completed soon

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
