### ISSUE TITLE
A DATA RACE about Notification in cluster.balancer.go

### ISSUE THREAD

**Issue by happyroc** [bsm/sarama-cluster#254]
we are using sarame-cluster in our project.Our code is like this:

```
consumer, err := cluster.NewConsumer(hosts, groupId, topics, cfg)
if err != nil {
    return err
}
for {
	select {
	case <-stop:
		return nil
	case notifies := <-consumer.Notifications():
		log.Info("notification triggered %v", notifies)
	case err := <-consumer.Errors():
		log.Error("consumer error, k=%v, err=%v", k, err)
	case event, eventsOk := <-consumer.Messages():
	    ...
	}
}
```

DATA RACE read occurs in this line:
```
log.Info("notification triggered %v", notifies)  // read Notification
```

DATA RACE write occurs in this place in balancer.go:
```
if n != nil {
	n.Type = RebalanceError   // write n.Type
	c.handleNotification(n)
}
```

the error stack is:

WARNING: DATA RACE
Write at 0x00c42b183fc0 by goroutine 114:
  github.com/bsm/sarama-cluster.(*Consumer).rebalanceError()
      /home/work/buildspace/8174d93485101396704252fca6611d34/golang/gopath/src/github.com/bsm/sarama-cluster/consumer.go:472 +0x29c
  github.com/bsm/sarama-cluster.(*Consumer).nextTick()
      /home/work/buildspace/8174d93485101396704252fca6611d34/golang/gopath/src/github.com/bsm/sarama-cluster/consumer.go:359 +0x66a
  github.com/bsm/sarama-cluster.(*Consumer).mainLoop()
      /home/work/buildspace/8174d93485101396704252fca6611d34/golang/gopath/src/github.com/bsm/sarama-cluster/consumer.go:328 +0xbe

Previous read at 0x00c42b183fc0 by goroutine 145:
...   
      /home/work/buildspace/xxx/cluster_sarama.go:68 +0x14d
...

maybe the func `rebalanceError` can transmit a copy of Notification?like this:

```
func (c *Consumer) rebalanceError(err error, n *Notification) {
	if n != nil {
		n.Type = RebalanceError
		
		// copy n
		nCopy := *n
		c.handleNotification(&nCopy)
	}
	...
}
```

or any other suggestion?

**Comment by dim** [comment]
Yes, it's a known problem which will be addressed in V3 - see #256
