### ISSUE TITLE
#Support : Way to get batch messages and commit if the batch is successful 

### ISSUE THREAD

**Issue by sanchitlohia-ovo** [bsm/sarama-cluster#274]
There doesn't seems a way to  implement the below flow

1. Read batch messages from Kafka.
2. Process all the messages.
3. If all messages processing succesful - Commit the offset
4. If any of the message processing fails - Do not commit the offset and read the same batch again and try to process the messages and if successful commit the offset.

**Comment by dim** [comment]
Unfortunately, there isn't, at least not easily. That's why I have put a lot of effort into https://github.com/Shopify/sarama/pull/1099 :) This repo is going to be deprecated in favour of the latest sarama release.
