### ISSUE TITLE
Does sarama-cluster  supports kafka 2.0?

### ISSUE THREAD

**Issue by langzi-zmg** [bsm/sarama-cluster#279]

**Comment by langzi-zmg** [comment]
Error: kafka: error while consuming applog/2: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876

**Comment by dim** [comment]
@langzi-zmg you need to set the correct `sarama.Config.Version` when connecting to Kafka, nothing to do with sarama-cluster. Also, since https://github.com/Shopify/sarama/pull/1099 was merged and released, this library is officially deprecated.
