### ISSUE TITLE
What is the behavior of consumer in multiplex mode ?

### ISSUE THREAD

**Issue by dhbarman** [bsm/sarama-cluster#287]
What is the behavior when a consumer is created in multiplex mode ? 

Suppose there are 10 partitions and one consumer-group. On each partition, the messages are available in order. But when a consumer consumes messages from the common channel, are the original order of messages per-partition preserved ? I understand that messages are put into the common channel.

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
