### ISSUE TITLE
How to get Notification() - rebalance notification in sarama lib

### ISSUE THREAD

**Issue by lingzhang000** [bsm/sarama-cluster#297]
Hello,
Since sarama-cluster already been deprecated and it is suggested to use sarama lib instead, is there any possibility to get Notification() in sarama lib? seems it has been deleted (any reason for that)... the reason for asking is we would like to do some customized logic when rebalance is triggered... thanks so much in advance...

**Comment by dim** [comment]
@lingzhang000 there is no need for it as you consume through a for loop in sarama's [ConsumerGroup](https://godoc.org/github.com/Shopify/sarama#ConsumerGroup). You can also define Setup/Cleanup callbacks on the [Handler](https://godoc.org/github.com/Shopify/sarama#ConsumerGroupHandler)
