### ISSUE TITLE
Not able to Read the messages from the reset offset for the partition

### ISSUE THREAD

**Issue by continuum-dipanjan-mazumder** [bsm/sarama-cluster#299]
I have implemented application checkpointing mechanism , in which the consumer before consuming messages from the partition , check the offset from where it needs to start reading from and then ResetPartitionOffset is called to set the offset to the required one. But after doing that it is not able to start reading immediately from that offset.If this is not possible what is the point of having the function.

Or is it that there is some way to do that with the library.

**Comment by dim** [comment]
please note https://github.com/bsm/sarama-cluster#deprecation-notice
