### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by kazaff** [bsm/sarama-cluster#300]
Hi there~
When I install ths library, I got error message:
```
go get github.com/bsm/sarama-cluster
# github.com/bsm/sarama-cluster
.go/src/github.com/bsm/sarama-cluster/consumer.go:452:59: c.client.config.Config.Consumer.Offsets.CommitInterval undefined (type struct { AutoCommit struct { Enable bool; Interval time.Duration }; Initial int64; Retention time.Duration; Retry struct { Max int } } has no field or method CommitInterval)

```
My GO version: 1.13

What can I do?

**Comment by kazaff** [comment]
[https://sourcegraph.com/github.com/Shopify/sarama@master/-/blob/config.go#L340:3](https://sourcegraph.com/github.com/Shopify/sarama@master/-/blob/config.go#L340:3)

The latest version of Sarama does not define `CommitInterval `...

**Comment by aoniboy** [comment]
yes  the latest version   
Renamed Consumer.Offsets.AutoCommitEnable to Consumer.Offsets.AutoCommit.Enable. Renamed Consumer.Offsets.CommitInteval to Consumer.Offsets.AutoCommit.Inteval

**Comment by dim** [comment]
Please note: https://github.com/bsm/sarama-cluster#deprecation-notice
