### ISSUE TITLE
Offsets.CommitInterval has change to Offsets.AutoCommit.Interval

### ISSUE THREAD

**Issue by kira3007** [bsm/sarama-cluster#304]
# github.com/bsm/sarama-cluster
src/github.com/bsm/sarama-cluster/consumer.go:452:59: c.client.config.Config.Consumer.Offsets.CommitInterval undefined (type struct { AutoCommit struct { Enable bool; Interval time.Duration }; Initial int64; Retention time.Duration; Retry struct { Max int } } has no field or method CommitInterval)

in sarama-cluster/consumer.go line 452 :

ticker := time.NewTicker(c.client.config.Consumer.Offsets.AutoCommit.Interval)

**Comment by dim** [comment]
Please note https://github.com/bsm/sarama-cluster#deprecation-notice
