### ISSUE TITLE
c.client.config.Config.Consumer.Offsets.CommitInterval undefined 

### ISSUE THREAD

**Issue by liusha0917** [bsm/sarama-cluster#307]
../github.com/bsm/sarama-cluster/consumer.go:452:59: c.client.config.Config.Consumer.Offsets.CommitInterval undefined (type struct { AutoCommit struct { Enable bool; Interval time.Duration }; Initial int64; Retention time.Duration; Retry struct { Max int } } has no field or method CommitInterval)

**Comment by liusha0917** [comment]
go build error

**Comment by omkarprabhu-continuum** [comment]
This is an issue @dim . Any update on this?

**Comment by omkarprabhu-continuum** [comment]
@liusha0917 install/update `Shopify/sarama` to latest version, that should fix this issue.

**Comment by mak28031991** [comment]
@omkarprabhu-continuum updating Shopify/sarama alone didn't work. I have to delete bsm and Shopify and update to fix this.
