### ISSUE TITLE
Using gopkg style dependency management creates issues

### ISSUE THREAD

**Issue by boyand** [bsm/sarama-cluster#32]
Hi, 

We have been using sarama-cluster for a while and it works pretty good. However using gopkg style dependencies creates a lot of issues such as problems when trying to use the mock subscribers/producers to write tests. (https://github.com/Shopify/sarama/issues/552). 

Would you consider switching to master imports and letting users be able to use their own dependency management ? ( such as vendoring or gopkg or whatever makes sense for them )

**Comment by dim** [comment]
Since vendoring is now supported natively, it's probably a good idea, could you submit a PR?

**Comment by dim** [comment]
Closed via #33
