### ISSUE TITLE
Option for not consuming the same message more than once

### ISSUE THREAD

**Issue by MateusDantas** [bsm/sarama-cluster#35]
Hello guys,

I work at a company (Top Free Games) and we are currently using sarama on one of our services. We are currently in process of migrating from Kafka 0.8.2 to Kafka 0.9.0, so we will be able to use the new Kafka-based offset tracking and consumer-group rebalancing.

We noticed that in a very particular case, when the service crashes, there's a possibility that we consume the same message more than once, since the message`s offset is committed periodically only. However, as we deal with end users, we can not afford to duplica messages as that would affect in a really bad way our user's experience. 

We could store the offsets on another database, but that would add another layer and possibly another point of failure to watch for, so that doesn't seem like a good option for us.

We came up with another solution: Store a batch of messages (e.g: 10k messages) at once, commit them right away and only then start using it as we have confirmation that they were committed. This sounds like a perfect solution for us, but we noticed that you don't export the method 'commitOffsets' that is responsible for committing the messages.

So my question is, would exporting this method be a solution or adding the whole functionality (consuming a batch of messages) would be more reasonable?

**Comment by MateusDantas** [comment]
Another solution would be to create a separate channel (e.g: safeMessages) so we can mark all the incoming messages as processed and then transfer all of them that were already committed to the separate channel. 

A possible solution would be: https://github.com/MateusDantas/sarama-cluster/commit/13158289da96e48ae00e981baa8c4d3d19efa084 (Still untested)

What do you guys think?

What do you guys think?

**Comment by dim** [comment]
Hey,

> We noticed that in a very particular case, when the service crashes, there's a possibility that we consume the same message more than once, since the message`s offset is committed periodically only

I am not sure how committing the offsets manually would solve the problem. What you consume your messages and your server crashes before you can issue e.g. a `CommitOffsets()` call?

I also don't see how a separate e.g. `Committed` channel would help in that situation. The only thing you realistically can do is ensure that services don't just 'crash', but are terminated gracefully. The consumer will always issue a final commit on `Close()`.

**Comment by MateusDantas** [comment]
We actually make a lot of effort into making sure our service will never crash, but sometimes unexpected things may happen (such as machines crashing by themselves), and we will not be able to terminate gracefully in such cases. I know it's a super rare condition and that it may never happen, but we can not afford to take those risks and duplicate messages for the end user as that would affect us in a really bad way.

Our first solution would be to first commit the offsets, and only then consume them. That would make sure that we never duplicate messages for the end user. A separated "Committed" channel would also help, because we would only consume committed messages. We know in that case there would be a chance that some messages get lost in case the system crashes, but that's acceptable for our case and duplicating messages is not acceptable in any way.

Hope we can find a common solution, as we really don't want to maintain another fork repo.

**Comment by MateusDantas** [comment]
Two solutions I propose:
1) Separated "Committed" channel with only messages that were already committed: https://github.com/MateusDantas/sarama-cluster/commit/13158289da96e48ae00e981baa8c4d3d19efa084
2) BatchOfMessages module that return a number X of messages after committing them: https://github.com/MateusDantas/sarama-cluster/commit/1531358a3c1b10c2d624881928e25e700ca24ab3

**Comment by MateusDantas** [comment]
Actually a very simple solution would be to just export https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L556 to enable us to commit offsets manually. I believe I'm not the only one that would like this feature to be present, as sarama already enables manual offset committing.

**Comment by dim** [comment]
Yep, was thinking among the same lines. So what you effectively want is to
turn Kafka's 'at least once' guarantee into 'at most once'.

Exporting commitOffsets is a little tricky but doable. It would allow you
to pull a batch of messages, then mark them as processed and finally commit
the offsets manually, before actually processing the messages.

Before I go ahead with this, a little word of warning. The approach above
will fix your immediate consumer problem, but it does not change Kafka's
core principles. If uniqueness of your messages is critical to your use
case, I would not rely on offsets. Messages are duplicated by Kafka and by
producers at a sufficiently regular basis. To assert uniqueness, you must
additionally employ one of the usual stream deduplication techniques.

**Comment by MateusDantas** [comment]
Yes, that's exactly what we want. We know that a message can be duplicated by producers at a regular basis, but we already have some checks in progress to prevent that on the producer. So based on the assumption that our producer will never produce the same message twice, we just need to guarantee that we will never consume the same message more than once. That's why exporting commitOffsets would be a great help for us, as that would allow me to do exactly what you described, thus guarantee uniqueness of our messages.

**Comment by dim** [comment]
Added in b3b9ad2a10642db7afbfb8d5b5fb2fc9345dfe8e
