### ISSUE TITLE
rebalancing is not happening when some threads go down

### ISSUE THREAD

**Issue by bpatelcs** [bsm/sarama-cluster#37]
Hi, 

I noticed that when I increase the consumer threads from 1 to 2 reading 1 topic with 4 partitions it is able to rebalance, but when I go from 2 to 1 thread then the running thread is not getting assigned the partitions which were assigned to the shut down thread, is it the limitation of this library or am I missing something?

**Comment by dim** [comment]
Hmm, this should not happen and it is not a limitation of the library. Are you sure you are using Kafka 0.9 and your consumers share the same group ID? I added a test in 122d1380662642f52d112e7e7e8d2c1e0c12e086 to demonstrate the functionality - works as expected.

**Comment by bpatelcs** [comment]
Yes, I was using kafka 0.9 and both the consumers were in the same group, I am not sure if anyone has noticed this since thread crash is very unlikely unless you mimic it.

**Comment by dim** [comment]
There is a constant heartbeat between the client and the Kafka server. If a thread/process/client dies, Kafka will know that it went offline and trigger a rebalance. I just tested this scenario locally by mimicking a crash of one of the threads and it does exactly as it should. You can try tweaking the `Config.Group.Heartbeat.Interval` setting but be careful not to set it too low. If that doesn't help, it's unlikely that your threads just 'die', it's more likely that your main goroutine is stuck or sleeping and that the heartbeat continues in the background.
