### ISSUE TITLE
Custom consumer ID?

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#4]
Right now the consumer generates its own ID (newGUID) because the customID field in ConsumerConfig is private.  Could you modify it so I can manually set the consumer ID in ConsumerConfig?

Awesome library, BTW.

**Comment by sbowman** [comment]
...or use the client ID.

**Comment by dim** [comment]
Any special reason for that? I don't know much about consumer IDs, except
that they must be unique for each consumer process/thread. Client ID
wouldn't work for that purpose, as a client might serve multiple consumers.

**Comment by sbowman** [comment]
My thought is that it can make it easier to track installations in larger systems using tools like Puppet and Chef.  You can coordinate the server names directly and match them up with what's in Zookeeper.

**Comment by dim** [comment]
Sure, but you can run many consumers (groups) on one server. You can even run multiple consumers in a single process in multiple goroutines. I am a little afraid of exposing this to users as bad and really unexpected things can happen if two consumers share the same ID.

The kafka documentation suggests:

> ... each consumer is given a transient, unique consumer_id (of the form hostname:uuid) for identification purposes ...

I could expose a configurable consumerID prefix which defaults to `hostname`, would that be an option?

**Comment by sbowman** [comment]
A configurable prefix would be a perfect compromise.

**Comment by dim** [comment]
Please let me know if #40274b35626a468189d2135f654afb5a07cb584e is what you are looking for

**Comment by sbowman** [comment]
Looks great.  Thanks for adding this.
