### ISSUE TITLE
Feature request: Seek functionality

### ISSUE THREAD

**Issue by jack8daniels2** [bsm/sarama-cluster#41]
It would be useful to include a seek function like java and python libraries.

http://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#seekToBeginning(org.apache.kafka.common.TopicPartition...)

https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/simple.py#L188

**Comment by dim** [comment]
I am a little confused. This functionality is implemented in github.com/Shopify/sarama where you can consume individual topic-partitions. The goal of sarama-cluster is to safely consume multiple topics/partitions via a cluster of concurrent consumers, forming a shared group. Please re-open if I misunderstood.
