### ISSUE TITLE
Single client w/ lot of consumers isn't stable

### ISSUE THREAD

**Issue by josselin-c** [bsm/sarama-cluster#46]
Hello,
I tried using a single Client for a lot (~120) of consumers (NewConsumerFromClient), each consuming a different topic of 8 partitions. Each consumer was alone in its consumer group (no other instance in the consumer group yet).
The consumers were all created during the same 4s window.

The consumers kept rebalancing one after another and it didn't seem to stabilize, even after waiting for 15minutes.
Sometimes i could see log such as: 
"kafka server: The provided member is not known in the current generation."

I tried increasing the Config.Net.MaxOpenRequests to 200 with no success. 

My other configs are:
Config.Net.ReadTimeout = 60 * time.Second
Config.Group.Session.Timeout = 25 * time.Second
Config.Group.Heartbeat.Interval = 6 * time.Second

Is that-many consumers for a single client just "too much" or should this works and you need more information?

BR

**Comment by dim** [comment]
Did you try the latest master? Can you enable logging and paste the trace?

**Comment by dim** [comment]
So I don't think that 120 consumers will put too much strain on a client, but that's more a question for the Sarama team, as they have probably more metrics for it. sarama-cluster internally creates a consumer per partition, so you must have enough connections to handle `consumers * topics * partitions`. Both, `Config.Group.Session.Timeout` and `Config.Group.Heartbeat.Interval` should match whatever is set on your Kafka server. 

Could you please repeat your experiment and enable verbose logging via `sarama.Logger = log.New(os.Stderr, "", log.LstdFlags)` [see doc](https://godoc.org/github.com/Shopify/sarama#StdLogger), this should give you a better indication of what's actually going on.

**Comment by dim** [comment]
I think this should be either resolved or mitigated through #59 and especially #60. Please re-open if this is still a problem
