### ISSUE TITLE
Consumer API not working

### ISSUE THREAD

**Issue by manavgarg** [bsm/sarama-cluster#47]
Hey,

I was using the sarama-cluster high level consumer API. However, I am not getting any messages. The consumer is not consuming anything. Can you please have a look. Here is my code (it is very similiar to one of the examples):

```
  config := cluster.NewConfig()
  config.Consumer.Return.Errors = true
  consumer, err := cluster.NewConsumer([]string{"localhost:9092"}, "CG1", []string{"my_topic2"}, config)
  if err != nil {
      panic(err)
  }

  defer func() {
      if err := consumer.Close(); err != nil {
          log.Fatalln(err)
      }
  }()

  // Trap SIGINT to trigger a shutdown.
  signals := make(chan os.Signal, 1)
  signal.Notify(signals, os.Interrupt)
  consumed := 0
  ConsumerLoop:
  for {
      select {
      case msg := <-consumer.Messages():
          log.Printf("Consumed message offset %d, %s\n", msg.Offset, string(msg.Value[:]))
          consumed++
      case <-signals:
          break ConsumerLoop
      }
  }

  log.Printf("Consumed: %d\n", consumed)
```

PS: The sarama API's for consumer is working for me with a similiar code fragment (I am using partionerconsumer to consume).

**Comment by dim** [comment]
Looks like you are consuming from the latest offset, not the earliest. Try to change `config.Consumer.Offsets.Initial`.

**Comment by manavgarg** [comment]
I tried using:
`config.Consumer.Offsets.Initial = sarama.OffsetOldest`
It still doesnt work

**Comment by Dieterbe** [comment]
@manavgarg what exactly is the error message? also be sure to set up things so you can see the errors, see the ticket i linked above

**Comment by sudersen** [comment]
The client work perfectly fine on centos however, there is something wrong on mac. Constantly getting the following error while connecting consumers.

`sarama-cluster-cli $ ./sarama-cluster-cli -brokers localhost:9093,localhost:9094,localhost:9095 -group test -offset oldest -topics test1
ERROR: Failed to start consumer: kafka server: Offset's topic has not yet been created.`

**Comment by dim** [comment]
Looks like you are requesting a topic that doesn't exist. Kafka can auto
provision topics but this is something that needs to be configured. This
error comes straight from Kafka and has unfortunately nothing to do with
sarama cluster.

**Comment by sudersen** [comment]
@dim Thanks!
This happened due to corrupted **__consumer_offsets**. Did a complete zookeeper and Kafka cleanup. Works like charm.
