### ISSUE TITLE
When I add partitions to a topic, consumer does not trigger a rebalance.

### ISSUE THREAD

**Issue by lrita** [bsm/sarama-cluster#48]
Kafka version : 0.9.0.1
When I add partitions to a topic, the producer will [send message to addition partition](https://github.com/Shopify/sarama/blob/master/async_producer.go#L329).
Because of kafka does not notify consumer by heartbeat api (Is this a kafka issue or normal behavior, but I cannot find this in jira of kafka?). So it dose not trigger a rebalance.
So, it looks like "I write some message in kafka, but I cannot read them".
Should we add an goroutine to check the change of the partition, or other good idea?

**Comment by dim** [comment]
So yes, currently the consumer only reads partitions on [rebalance](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-JoinGroupResponse) and does not actively listen to partition changes. This is different to the sarama producer, which performs periodic background reloads and is therefore able to pick up new partitions. 

I had a quick look at the docs and it seems that the consumer group would have to periodically call [SyncGroup](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-SyncGroupRequest) to pick up new partitions automatically, but I wonder what the actual impact might be. I am a little worried that it may have adverse effects, e.g. all consumers constantly spinning and rebalancing. I will see if I can test it, but any additional insight would be very appreciated.

**Comment by lrita** [comment]
Thanks for your reply.
There are some details conflict with this issue.
When we set [Config.Consumer.Offsets.Initial](https://github.com/Shopify/sarama/blob/master/config.go#L208) = OffsetNewest.
During adding partitions to a topic, maybe producer writes message to the new addition partitions before consumer start to read those partitions whatever we are using some method to trigger rebalance.
Unfortunately, message has been lost in fact.
In my opinion, when I use OffsetNewest, it means I want to read messages from the time I started consumer, but I am not tolerant of messages lost.
So, is it raised an except behavior?

**Comment by dim** [comment]
Please checkout https://github.com/bsm/sarama-cluster/pull/102 (not merged yet)

**Comment by liudanking** [comment]
I meet the same problem with latest master and v2.1.5.

Sample code is as follows:

```
func groupConsume() {

	// init (custom) config, enable errors and notifications
	config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true

	// init consumer
	topics := []string{TOPIC}
	consumer, err := cluster.NewConsumer(brockerList, "my-consumer-group", topics, config)
	if err != nil {
		panic(err)
	}
	defer consumer.Close()

	// watch errors
	go func() {
		for err := range consumer.Errors() {
			log.Printf("Error: %s\n", err.Error())
		}
	}()

	// watch notifications
	go func() {
		for note := range consumer.Notifications() {
			log.Printf("Rebalanced: %+v\n", note)
		}
	}()

	// trap SIGINT to trigger a shutdown.
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	// consume messages
	for {
		select {
		case msg := <-consumer.Messages():
			log.Printf("consumer: %s/%d/%d\t%s\t%s", msg.Topic, msg.Partition, msg.Offset, msg.Key, msg.Value)
			consumer.MarkOffset(msg, "") // mark message as processed
		case <-signals:
			return
		}
	}
}
```

**Comment by dim** [comment]
The consumer only watches for new topics so it will not aware of new partitions being added. That said, I haven't checked Kafka's documentation about this, but I would expect the Kafka broker to trigger a rebalance of consumers when new partitions are added at runtime. Maybe it's something to bring up on the Kafka bug tracker

**Comment by nsd20463** [comment]
I too have noticed that kafka brokers don't bump the generation numbers of consumer groups when partitions are added to a topic. That might be an oversight. Or it might be because the kafka broker doesn't know what topics are being consumed by a group in the general case.

It could know the topics consumed by groups where the JoinGroupRequest.ProtocolType is "consumer", and consumers used a ConsumerGroupMemberMetadata.Version it understood, which is true in this case today, but restrictive in general.

**Comment by bataras** [comment]
as of 5/27/18, running from master. A consumer is not seeing new partitions that get added to currently-consumed topic. Using essentially the same code the @liudanking posted above
