### ISSUE TITLE
Doesn't confirm partition offset?

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#5]
It doesn't look like sarama-cluster is confirming the message offset for a topic partition stored in Zookeeper against what's actually in Kafka.  I'm seeing an error message that the requested message offset doesn't exist in Kafka.

I had this issue before when I was just using straight sarama.  If I stored a partition offset in Zookeeper, and either (a) didn't run my app for a while so the partition offset was removed from Kafka or (b) manually cleared all the Kafka data and restarted from scratch, the Zookeeper partition offset would be off.  When it tried to ask Kafka for a message, Kafka returns an "offset doesn't exist" error or something like that.

I looked in your code and couldn't find a reference to "GetOffset", so I assume you're not checking offsets.  I haven't had a chance to look at the problem deeply, but I thought you might know off the top of your head if I'm just missing something, or this really isn't implemented.

What I did was confirm the offset with Kafka when my app started.  If my offset was older than the earliest value in Kafka, I reset my value to that value and logged an info message.  If my offset was higher than Kafka's, I reset to 0 and logged a warning, assuming that data had been wiped.  Maybe this is a little presumptuous, but it worked well enough for my app.

**Comment by sbowman** [comment]
For some more info:  in ZK, my app has an offset ID for partition 0 of something like 624312.  When I query Kafka about partitions, it looks like 624312 is the earliest message.  But the error I'm getting from the event in my app is that sarama/sarama-cluster is asking for message offset 0, and obviously message offset 0 doesn't exist.

**Comment by sbowman** [comment]
We've confirmed the following scenario:

* Our Kafka client has been running normally, but is offline.
* Kafka clears old messages.
* The message offset in ZK for our Kafka client doesn't exist anymore in Kafka.
* The Kafka client starts up and requests messages from Kafka.
* Kafka reports the offset requested doesn't exist.

I had this problem in my app before I started using the sarama-cluster.  Like described above, I solved it by confirming the message offset in ZK before I started asking for message offsets.  If the message offset I had in ZK was lower than the earliest offset reported by Kafka, I adjusted my message offset to match Kafka's and logged a message.

**Comment by dim** [comment]
Hmmm, thanks for the detailed notes, I see the problem now. If the stored offset is < than the offset on the server, then https://github.com/bsm/sarama-cluster/blob/40274b3/consumer.go#L317 would return an error. Is an error message logged? You can assign a custom logger to the package via https://github.com/bsm/sarama-cluster/blob/40274b3/cluster.go#L9 or register your own notifier to handle errors (https://github.com/bsm/sarama-cluster/blob/40274b3/cluster.go#L13)

**Comment by dim** [comment]
Check this out https://github.com/bsm/sarama-cluster/commit/a5c6d86befa560ac9af69d6b2dbbce0fd99d792d. Please let me know if it worked.

**Comment by sbowman** [comment]
I don't think this is working.  I'm not seeing ConsumePartition() returning a sarama.ErrOffsetOutOfRange.  I think I'm not getting the error until sarama actually tries to pull messages.

**Comment by sbowman** [comment]
Here's my fix:

```
func (c *Consumer) claim(partitionID int32) (sarama.PartitionConsumer, error) {
	err := c.zoo.Claim(c.group, c.topic, partitionID, c.id)
	if err != nil {
		return nil, err
	}

	earliest, err := c.client.GetOffset(c.topic, partitionID, sarama.EarliestOffset)
	if err != nil {
		return nil, err
	}

	latest, err := c.client.GetOffset(c.topic, partitionID, sarama.LatestOffsets)
	if err != nil {
		return nil, err
	}

	offset, err := c.Offset(partitionID)
	if err != nil {
		return nil, err
	}

	if offset < earliest || offset > latest {
		offset = sarama.OffsetOldest
	}

	return c.consumer.ConsumePartition(c.topic, partitionID, offset)
}
```

**Comment by sbowman** [comment]
I my sample code, I set offset to OffsetOldest even when the offset is greater than the latest number, because I'm assuming someone has mucked with the partitions and reset them.

**Comment by dim** [comment]
Yep, I (re-)fixed this in https://github.com/bsm/sarama-cluster/commit/723a135. The error appears in the `Errors()` channel, not on claim. Even found a way to test it. https://travis-ci.org/bsm/sarama-cluster. Will push a v1.0.2 tomorrow
