### ISSUE TITLE
Tried to use sarama-cluster library to write sample consumer code ... but during go build my code I am getting error from sarama-cluster library ...

### ISSUE THREAD

**Issue by SubrataPucsd** [bsm/sarama-cluster#50]
I'm trying to write a simple consumer code using sarama-cluster library ....
But during go build of my code ... I'm getting bellow error from your library ... ?
Already sarama library is also there ....
==============
# github.com/bsm/sarama-cluster
github.com/bsm/sarama-cluster/balancer.go:93: undefined: sarama.ConsumerGroupMemberMetadata
github.com/bsm/sarama-cluster/config.go:82: c.Config.Consumer.Offsets undefined (type struct { Retry struct { Backoff time.Duration }; Fetch struct { Min int32; Default int32; Max int32 }; MaxWaitTime time.Duration; Return struct { Errors bool } } has no field or method Offsets)
github.com/bsm/sarama-cluster/consumer.go:270: undefined: sarama.ErrRebalanceInProgress
github.com/bsm/sarama-cluster/consumer.go:286: c.client.config.Config.Consumer.Offsets undefined (type struct { Retry struct { Backoff time.Duration }; Fetch struct { Min int32; Default int32; Max int32 }; MaxWaitTime time.Duration; Return struct { Errors bool } } has no field or method Offsets)
github.com/bsm/sarama-cluster/consumer.go:307: undefined: sarama.ErrRebalanceInProgress
github.com/bsm/sarama-cluster/consumer.go:334: c.client.config.Config.Consumer.MaxProcessingTime undefined (type struct { Retry struct { Backoff time.Duration }; Fetch struct { Min int32; Default int32; Max int32 }; MaxWaitTime time.Duration; Return struct { Errors bool } } has no field or method MaxProcessingTime)
github.com/bsm/sarama-cluster/consumer.go:356: broker.Heartbeat undefined (type *sarama.Broker has no field or method Heartbeat)
github.com/bsm/sarama-cluster/consumer.go:356: undefined: sarama.HeartbeatRequest
github.com/bsm/sarama-cluster/consumer.go:383: undefined: sarama.ErrUnknownMemberId
github.com/bsm/sarama-cluster/consumer.go:394: undefined: sarama.ErrRebalanceInProgress
github.com/bsm/sarama-cluster/consumer.go:394: too many errors
=====================

**Comment by dim** [comment]
Please try `go get -u ./...`
