### ISSUE TITLE
new consumer connects fine but subscriptions is empty?

### ISSUE THREAD

**Issue by Dieterbe** [bsm/sarama-cluster#51]
Hi, i'm a bit new to kafka, sarama and sarama-cluster.
I have a simple publisher like so https://github.com/raintank/raintank-metric/blob/c6eae22ef4acf868a2f5949436720d7c834b0fbf/fake_metrics/out/kafkamdm/kafkamdm.go
my kafka (i tried both 0.9 and 0.10) has 1 broker and my topic has 1 partition and production to the topic is working fine. i can confirm the number of partitions and message rate with kafka manager.

I also have a simple consumer https://github.com/raintank/raintank-metric/blob/c6eae22ef4acf868a2f5949436720d7c834b0fbf/metric_tank/in/kafkamdm/kafkamdm.go using sarama-cluster.
it logs "kafka-mdm consumer started without error" but immediately gets notification messages like so:
```
(*cluster.Notification)(0xc4200e3660)({
 Claimed: (map[string][]int32) {
 },
 Released: (map[string][]int32) {
 },
 Current: (map[string][]int32) {
 }
})
```
When I run 	log.Info("kafka-mdm subscriptions: %v", k.consumer.Subscriptions()) I get `map[]` back.

any idea why it may not be picking up the partition(s) to read from?
If this is the wrong place to ask, do you have a recommendation for where I should ask?

thanks,
Dieter

**Comment by Dieterbe** [comment]
cause was simply that we have to explicitly declare which kafka protocol version to use with the latest sarama code.  this is needed for both 0.9 and 0.10 , it wasn't documented yet in sarama .

**Comment by mcandre** [comment]
Where is this documented now? How should users configure sarama and/or sarama-cluster in order to specify the Kafka protocol version?
