### ISSUE TITLE
we should make it easier to view errors by default

### ISSUE THREAD

**Issue by Dieterbe** [bsm/sarama-cluster#53]
the way `Consumer.handleError` currently works seems like a suboptimal default:

`c.client.config.Consumer.Return.Errors` defaults to false, so we call sarama.Logger.Println, which defaults to io.Discard.

this means that any error is silently dropped by default, and this is non-obvious.

**Comment by Dieterbe** [comment]
an example of how I ran into this: I was troubleshooting #51, I saw a note about JoinGroup possibly returning errors in #47, so I added some print statements, which showed me `kafka server: The version of API is not supported` .  Then I reverse engineered how error handling worked and saw that by default errors are not shown as explained above.

**Comment by dim** [comment]
This is (maybe unfortunately) the default sarama uses to operate. I think that `sarama.Logger` should not discard messages by default, but that's not really something I can influence. Please re-open if you have an idea on how to make this better, I can't see one, given the constraints from sarama

**Comment by Dieterbe** [comment]
maybe c.client.config.Consumer.Return.Errors = true by default?

**Comment by dim** [comment]
Again, this is a sarama default, not one of ours

**Comment by chandradeepak** [comment]
we ran it to same problem you can set the sarama.Logger = &SaramaLogger{}
where SaramaLogger is a struct which implements below three functions which are part of interface. That is the work around we had for now. But i agree sarama should better log errors.

 `func (sl *SaramaLogger) Print(v ...interface{}) {
	log.Println(fmt.Sprint(v...))

}
func (sl *SaramaLogger) Printf(format string, v ...interface{}) {
	log.Println(fmt.Sprintf(format, v...))

}
func (sl *SaramaLogger) Println(v ...interface{}) {
	log.Println(fmt.Sprintln(v...))
}`

**Comment by dim** [comment]
Your workaround could be simpler and faster if you just:

```go
sarama.Logger = log.New(os.Stderr, "", log.LstdFlags)
```
