### ISSUE TITLE
mission statement / introduction / readme should be clearer

### ISSUE THREAD

**Issue by Dieterbe** [bsm/sarama-cluster#54]
the readme says 

> Package cluster provides cluster extensions for Sarama, enabing users to consume topics across from multiple, balanced nodes.

This seems rather vague. I think I can run a cluster without sarama-cluster, with straight sarama just fine.  We can also consume topics from multiple nodes using sarama.  So is it all about the "balanced" part? What does this mean exactly, balanced? I can run a kafka cluster and use plain sarama consumers that are well balanced. So what does sarama-cluster do?  I'm guessing it has to do with automatically managing something that otherwise has to be managed manually. But what exactly?  What are some scenarios where this library becomes useful? When should we use it, and when not?

Then in https://github.com/bsm/sarama-cluster/issues/41 it is said

> The goal of sarama-cluster is to safely consume multiple topics/partitions via a cluster of concurrent consumers, forming a shared group.

Safe in what way? What is otherwise unsafe and how does sarama-cluster make it safe? What is a shared group, and who is the group being shared with?

Does sarama-cluster make certain assumptions about the intended use? Like perhaps "the same message should not be processed by multiple consumers" ? Any such assumptions should be clarified.

thank you.

**Comment by dim** [comment]
The comments are based on the Kafka's native cluster consumer. I am more than happy to improve the documentation, but given our current workload, I would really appreciate a PR.

**Comment by dim** [comment]
Closing for now, please re-open as a PR
