### ISSUE TITLE
should close broker when broker error has occurred.

### ISSUE THREAD

**Issue by lrita** [bsm/sarama-cluster#57]
When broker error has occurred, we should close broker to make re-connect to broker.

If we do not re-connect to the broker, the broker report error for ever. eg: broker server has restart some time or [some bug](https://issues.apache.org/jira/browse/KAFKA-3593), the previous connection of broker will be broken. If we do not re-connect to the broker, other commands will return `EPIPE` ever.

referrer [https://github.com/Shopify/sarama/blob/master/client.go#L702](https://github.com/Shopify/sarama/blob/master/client.go#L702)

**Comment by dim** [comment]
When client closes a broker it also needs to [deregister](https://github.com/Shopify/sarama/blob/master/client.go#L703) it, that's why it's not a solution. Will investigate an alternative

**Comment by dim** [comment]
Closed by #59

**Comment by lrita** [comment]
@dim 
In my opinion, calling `func (b *Broker) Close() error` without `sarama.Client` will not cause any issues. Because `sarama.Client` will re-open  cached broker before using it.
e.g. [func (client *client) Coordinator(consumerGroup string) (*Broker, error)](https://github.com/Shopify/sarama/blob/master/client.go#L355), [func (client *client) any() *Broker](https://github.com/Shopify/sarama/blob/master/client.go#L431), [func (client *client) cachedLeader(topic string, partitionID int32) (*Broker, error)](https://github.com/Shopify/sarama/blob/master/client.go#L509).

And, calling `RefreshCoordinator(consumerGroup string) error` cannot resolve this issue. Because `RefreshCoordinator` cannot really refresh the connection of broker when it is closed by Kafka broker server. The reason is [func (client *client) registerBroker(broker *Broker)](https://github.com/Shopify/sarama/blob/master/client.go#L381) omit new broker when they has the same `ID()` and `Addr()`.

**Comment by dim** [comment]
Can you pls review #61. Closing this one in favour of it

**Comment by lrita** [comment]
@dim 
#61 LGTM, thanks for your reply.
