### ISSUE TITLE
Breaking change in Shopify/sarama

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#6]
They refactored the consumer event processing, breaking apart events into messages and errors and adding a "PartitionConsumer" layer (as opposed to what other type of consumer?).

**Comment by dim** [comment]
I'm working on an update and have found a problem with sarama - https://github.com/Shopify/sarama/issues/325. Will resume once I have a solution or a workaround.

**Comment by dim** [comment]
Pushed as v1.0.0 and exported as gopkg.in/bsm/sarama-cluster.v1

**Comment by sbowman** [comment]
go get -u gopkg.in/bsm/sarama-cluster.v1
# gopkg.in/bsm/sarama-cluster.v1
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:150: cannot use scsmr (type sarama.Consumer) as type *sarama.Consumer in field value:
	*sarama.Consumer is pointer to interface, not interface
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:298: pcsm.Messages undefined (type *sarama.PartitionConsumer has no field or method Messages)
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:313: pcsm.Errors undefined (type *sarama.PartitionConsumer has no field or method Errors)
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:342: c.consumer.Close undefined (type *sarama.Consumer has no field or method Close)
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:399: c.Close undefined (type *sarama.PartitionConsumer has no field or method Close)
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:435: c.consumer.ConsumePartition undefined (type *sarama.Consumer has no field or method ConsumePartition)
../../../../gopkg.in/bsm/sarama-cluster.v1/consumer.go:437: c.consumer.ConsumePartition undefined (type *sarama.Consumer has no field or method ConsumePartition)

**Comment by dim** [comment]
Try github.com/bsm/sarama-cluster
