### ISSUE TITLE
Offset manager got wrong behavior after commit 6fdf904

### ISSUE THREAD

**Issue by lrita** [bsm/sarama-cluster#63]
When we consumed a message from per partition and [`MarkOffset`](https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L106-L108) these messages, but the offsets will not auto `CommitOffsets` by consumer timeout.

The offset of the first message we got from per-partition is equal to the offset we got from [`fetchOffsets`](https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L412).
[Here](https://github.com/bsm/sarama-cluster/blob/master/partitions.go#L111) being modify to `if offset >= c.state.Info.Offset {`, it will be normal behavior.

**Comment by dim** [comment]
Fixed in https://github.com/bsm/sarama-cluster/commit/5c61d208e29b14f079a6422822e61eefd48784ac
