### ISSUE TITLE
Unable to listen to messages with cluster.Consumer

### ISSUE THREAD

**Issue by mslepak** [bsm/sarama-cluster#66]
I must be doing something wrong. I can successfully publish and consume kafka 0.9 messages with plain sarama, i.e. when I am publishing to a specific partition and listening on that partition. However, when I attempt to use cluster.Consumer I can no longer consume any published messages. In this scenario, I am using sarama.SyncProducer, initialized with NewSyncProducer(). Consumer is initialized with cluster.NewConsumer(). Any help will be greatly appreciated.

**Comment by nomoonx** [comment]
same here.

**Comment by dim** [comment]
Looks like there is an incompatibility with the latest [release](https://github.com/Shopify/sarama/releases), will review later today

**Comment by dim** [comment]
As suggested, sarama 1.10.0 requires a protocol version to be set, released a [new version](https://github.com/bsm/sarama-cluster/releases)
