### ISSUE TITLE
Multiple topics

### ISSUE THREAD

**Issue by sbowman** [bsm/sarama-cluster#7]
I have a single app listening to two different topics.  What I'm seeing is that both topics start processing, but one stop after a few messages and never picks up again.  If I run two separate copies of my app, each pointing at one topic or the other, then processing occurs normally.

I've tried sharing the same sarama client and using two different ones, but I still see the conflict.  Also tried messing with GOMAXPROCS.

I'm not sure if it's something in sarama-cluster or sarama itself.  I'll investigate deeper into the problem and see if I can uncover something.

**Comment by lukanus** [comment]
You are probably not reading from errors channel. It does matter especially in older version of sarama  (and in older documentation you might found the notice saying that if you won't do that, sarama will behave in exactly the way you've described - happened to me before). Also check how many partitions you have in kafka vs how many you are consuming from - because that might also be and issue.

**Comment by dim** [comment]
Yep, please check the example too https://github.com/bsm/sarama-cluster/blob/master/_examples/simple.go#L56

**Comment by sbowman** [comment]
I think I found the problem.  When I create a new sarama.Client to pass to cluster.NewConsumerFromClient, I have to create a Config that sets Consumer.Return.Errors = true.  Otherwise sarama gobbles up the error messages (well, writes them to stdout).

Once I did that, sarama started sending the errors to sarama-cluster, and sarama-cluster was able to adjust the offsets properly using your new code.

Working great now.  Thanks!

**Comment by dim** [comment]
Hmm, this is something the library should at least warn the user about, or
override the value to true by default and 'gobble up' the error messages
itself. Could you please reopened? I'll fix it tomorrow.

**Comment by sbowman** [comment]
I don't have permission to reopen the ticket, so I created a new one more appropriate to the issue:

https://github.com/bsm/sarama-cluster/issues/9

Since I'm the one creating the sarama.Client, I don't know that there's anything you can really do, other than document it better than the Shopify folks.
