### ISSUE TITLE
Feature Request: Expose Consumer Group Member UserData

### ISSUE THREAD

**Issue by msample** [bsm/sarama-cluster#70]
For Example,  Add  Config.Group.Member.UserData []byte and propagate with JoinGroup requests.

The Kafka protocol appears to allow consumer group members to provide 'user data' for partition assignment balancing protocols.  This user- data is shared with the balancer, which is selected from one of the members of the consumer group. The balancer then allocates partitions to the group members, possibly based on the user-data.

Even though the current sarama-cluster balancer implementation does not act on user-data it provides value to external tools:  E.g. external routing of a web request to a specific partition-owner in consumer group (if the user data contained http host:port info).

External tools could extract this info from the broker without joining the group by something like:

```
client, err := scluster.NewClient(...)
broker, err := client.Coordinator(groupName)
req := &sarama.DescribeGroupsRequest{Groups: []string{groupName}}
resp, err := broker.DescribeGroups(req)
groupDesc := resp.Groups[0]
```

Not sure how one would watch for changes to the partition assignments without being part of the consumer group though.  In a reasonably stable environment this may not be too bad so long as there is a fall back for routing (e.g. a redirect).

**Comment by dim** [comment]
Sounds like a good idea, but could you please submit a PR?

**Comment by msample** [comment]
Sure, I'll try to get to it in the next few weeks.

**Comment by dim** [comment]
Closing for now, please re-open as a PR
