### ISSUE TITLE
MarkPartitionOffset has no effect

### ISSUE THREAD

**Issue by lkpjj** [bsm/sarama-cluster#73]
Hi @bsm 
    In my program ,we want read messages on partition0 from the position:offset0,but there is no effect below:
**_MarkPartitionOffset(my_test_topic,partition0,offset0,"")_**

Or is there a way to achieve such requirements？

Looking forward to your reply,thanks.

**Comment by flisky** [comment]
There are `cmLoop` to commit offsets periodically. Or you can call `CommitOffsets` directly.

**Comment by lkpjj** [comment]
In fact, the partition consumer is already running,when you commit an old offset,the partition will not read from that offset position only if the partition consumer recreated.

**Comment by dim** [comment]
There is no sensible way to "rewind" to a previous offset in sarama-cluster. Given your requirements, I would probably use [Sarama](https://github.com/Shopify/sarama) directly.
