### ISSUE TITLE
Improve docs regarding examples

### ISSUE THREAD

**Issue by apinnecke** [bsm/sarama-cluster#75]
Hey all,

first of all thanks for this awesome library! I's actually saving A LOT of time! 💪 

Unfortunately there is a small lack of documentation regarding examples - READMY says `Documentation and example are available via godoc [..]` but godoc doesn't contain examples?

I've got my consumer implementation running, but this was paired with a lot of reading `sarama-cluster`s source code and the cli tool, which should be the case, no? Would be great if you/we could add some examples to docs. :)

Have a nice day and greetings from Germany!
Alex

**Comment by dim** [comment]
I would really appreciate some help with documentation and examples. Could you please submit a (separate) pull request?

**Comment by apinnecke** [comment]
I'm not seeing this one closed. I'd close this one as soon as the PR is merged? Anyway, I'll try and tackle this asap.
