### ISSUE TITLE
How to disable auto commit?

### ISSUE THREAD

**Issue by apinnecke** [bsm/sarama-cluster#76]
Hey all,

currently trying to figure out how I disable auto commit. I'd like to commit a message by hand after processing it to avoid false positive message commits - the only way I've found so far is to set `config.Consumer.Offsets.CommitInterval` to sth. > 10 sec, more likely 1m ... but this doesn't seem to be the preferred way, no? At least it feels a bit wrong. :D

Either way this should be documented somewhere - partly related to #75  and maybe related to #73❔ 

Have a nice day and greetings from Germany!
Alex

**Comment by dim** [comment]
Hey!

You can disable retention via https://github.com/Shopify/sarama/blob/master/config.go#L218. Alternatively, you can just not call https://godoc.org/github.com/bsm/sarama-cluster#Consumer.MarkOffset. Without changes to offsets, commits will be skipped. 

Grüße aus London,
Dim

**Comment by apinnecke** [comment]
Thanks for the quick response!

Well, I'm not calling `Consumer.MarkOffset` and haven't configured `Consumer.Offsets.Retention`.  Assuming I'm understanding the docs for the config correctly the default retention time of Kafka is used, which default to 24 Hours.

Kafka docs are saying as follows:
> The Kafka cluster retains all published messages—whether or not they have been consumed—for a configurable period of time. For example if the log retention is set to two days, then for the two days after a message is published it is available for consumption, after which it will be discarded to free up space. Kafka's performance is effectively constant with respect to data size so retaining lots of data is not a problem.

So ... why doesn't my consumer receive a message twice then? Am I missing an obvious part? 💭

**Comment by dim** [comment]
I assume your consumer is configured to start with the latest offset, not
the easiest.

**Comment by AlbinOS** [comment]
@apinnecke, if you have found a Kafka or Sarama configuration to do that, I'm very interested as well.

Either I can have all message when starting a consumer (largest,oldest) or any (smallest, newest)... I don't understand how to use commit or mark.

**Comment by yoshiyaka** [comment]
I agree that having the ability to disable auto commit would be nice. We have a scenario where we read data from kafka, calculate som stats from it, and periodically commit those stats to our database. It roughly looks something like the following pseudo code:

```
lastCommit := 0
sum := 0
for msg := range consumer.Messages() {
    sum += msg.SomeStat
    consumer.MarkOffset(msg, "")
    if lastCommit < 5 minutes ago {
        flushSumToDatabase(sum)
        consumer.CommitOffsets()
        lastCommit = time.Now()
        sum = 0
    }
}
```

Auto commit gives us some trouble in this case, as we might commit offsets which we have not yet written to the database. Having the ability to disable it by simply setting `config.Consumer.Offsets.CommitInterval = 0` would be great.

**Comment by dim** [comment]
To disable auto-commit, simply delay your `MarkOffset` calls. A commit will only occur when the offsets have been changed. If you are not ready to commit, then don't mark the offset as ready.

**Comment by yoshiyaka** [comment]
Yes, this solves the problem, however the resulting code would not be very clean when bulk-processing messages arriving from several different partitions. One would need to keep track of the latest message seen on each partition so that the may be sent to `MarkOffset` later. The code from my comment above would instead look like:

```
lastCommit := 0
sum := 0
lastMessageByPartition := map[int]consumer.Message{}
for msg := range consumer.Messages() {
    sum += msg.SomeStat
    lastMessageByPartition[msg.Partition] = msg

    if lastCommit < 5 minutes ago {
        flushSumToDatabase(sum)

        for _, m := range lastMessageByPartition {
            consumer.MarkOffset(m, "")
        }
        lastMessageByPartition = map[int]consumer.Message{}
        consumer.CommitOffsets()
        lastCommit = time.Now()
        sum = 0
    }
}
```

The way I see it is that in some cases, it would be nice to disable auto commit, and I don't think that it would have any downsides to the library or make it more complicated? It could be easily implemented using a simple `if c.client.config.Consumer.Offsets.CommitInterval == 0` somewhere around https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L243

**Comment by yoshiyaka** [comment]
So, should I create a PR for this?

**Comment by dim** [comment]
Sure, please

**Comment by dim** [comment]
Closing for now, please re-open via PR

**Comment by dim** [comment]
You could set the CommitInterval to (pretty much) infinity, but a read-only PartitionOffsetManager makes little sense as every state about offset will be lost after a rebalance. BTW, sarama-cluster is now semi deprecated, as I am working on a ConsumerGroup feature directly in sarama - https://github.com/Shopify/sarama/pull/1099

**Comment by snigle** [comment]
> To disable auto-commit, simply delay your `MarkOffset` calls. A commit will only occur when the offsets have been changed. If you are not ready to commit, then don't mark the offset as ready.

Sometime we want to markoffset and don't commit. To permits to block the rebalance until the process is done (with rebalance timeout).

**Comment by dim** [comment]
@snigle there is no way to do this consistently in sarama-cluster due to a lack of coordination between server-side rebalances and manual commits. This issue has been addressed as part of my effort for https://github.com/Shopify/sarama/pull/1099 which allows highly customised workflows.
