### ISSUE TITLE
Which design is this library based on?

### ISSUE THREAD

**Issue by usmanm** [bsm/sarama-cluster#77]
The docs say the consumer is based on: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design

But that's apparently an obsolete design and the page links to an updated design which should be used with Kafka 0.9+: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal

Are the docs wrong or is this actually based on the obsolete design?

**Comment by dim** [comment]
Yeah, you're right, the docs are wrong. The consumer design is based on the
new API provided by Kafka 0.9+, the same the native Scala implementation is
using. A PR fixing the documentation would be more than welcome.

Thanks,
Dim

**Comment by usmanm** [comment]
Awesome, I'll submit a PR soon.
