### ISSUE TITLE
Question about OffsetManager

### ISSUE THREAD

**Issue by guangchl** [bsm/sarama-cluster#78]
I want to use this repo, but I am confused by some questions. And I am not sure is here a good place to ask questions.

1. It was mentioned in sarama repo in this thread: https://github.com/Shopify/sarama/issues/619. @dim said he will have to rewrite some parts of OffsetManager, is the work all done? I mean I should be able to commit/fetch offset of a topic/partition by using this sarama-cluster package alone, right?

2. Here are some of my understandings, just saying out laud. After creating a consumer group, if I add more consumers into the group, the load (as in partitions) will be rebalanced to those new consumers? And the opposite, if some consumers down in the same group, the load will be rebalanced to other consumers in the group?

3. Is there any good and clean example of using this package?

I appreciate any answer and correction.

Thanks.

**Comment by dim** [comment]
Hi,

1. I am using my own OffsetManager, as sarama can only maintain offsets per topic/partition and cannot commit in bulk. This would cause a significant bottle-neck for sarama-cluster
2. yes and yes.
3. Sure, check the bundled [CLI consumer](https://github.com/bsm/sarama-cluster/blob/master/cmd/sarama-cluster-cli/main.go). You can run multiple times in separate terminals and the workload will be evenly distributed.

**Comment by guangchl** [comment]
Hi @dim ,

Thanks for the answer. The example is awesome too. I have some follow up questions about offset, hope I am not bothering you too much.

1. I noticed there is no fetch API for offset. This makes sense since what we want to do when adding or replacing a consumer in a consumer group is just mark "config.Consumer.Offsets.Initial = sarama.OffsetNewest" for the new consumer?

2. MarkOffset is totally local operation, but commit is sending the marked offset to Kafka?

3. A little confused about metadata returned by [MarkOffset](https://godoc.org/github.com/bsm/sarama-cluster#Consumer.MarkOffset). It is just for local usage, which means same process can initiate another consumer to continue the work? On the other hand, CommitOffset doesn't return that because the info is already stored in Kafka?


Thanks

**Comment by dim** [comment]
1. the consumer internally retrieves the offsets for the partitions it "ownes". the ownership is determined by the coordination process, as described in https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal
2. yes, commits occur periodically in the [background](https://github.com/Shopify/sarama/blob/3f8bfbafaba08d203c680fe35f2eb9a46b49a509/config.go#L206) or on consumer rebalances (or when `Close()` is called)
3. you can pass some and update metadata when marking offsets which will be committed to kafka. At the moment the metadata is not used but you could potentially implement a custom rebalancing algorithm that relies on metadata as described in the [proposal](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal) document.

> Metadata-based assignment: In some cases, it is convenient to leverage consumer-local metadata to make assignment decisions. For example, if you can derive the rack from the FQDN of the Kafka brokers (which is common), then it would be possible to have rack-aware consumer groups if there was a way to communicate each consumer's rack to the partition assignment.

You could pass a special metadata value to the offset storage. When rebalancing, you could then ensure that topics that carry a certain metadata value are processed by a special cluster of consumers. This could be e.g. useful if you have partitions and consumers running across multiple data-centres and want to enforce affinity.
