### ISSUE TITLE
Is it possible to re-start from the last committed offset after rebalance?

### ISSUE THREAD

**Issue by recurser** [bsm/sarama-cluster#79]
I'm working on a system that accumulates summary data in memory for a variety of metrics over the last 5 minutes, running on several different servers. The raw data is keyed on metric name, so a consumer always gets data for the same set of metrics. At the start of each minute I mark an offset from 5 minutes ago, so if the service is restarted it can re-calculate the summary data. 

However, when a rebalance occurs, consumers start getting data for other metrics that they don't know the 5-minute-history of. When a rebalance occurs, I'd like to re-read all of the data from the last 5 minutes (ie. the last commit point). Is it possible to jump back to this offset after a rebalancing event occurs, without actually closing the connection and reconnecting to Kafka? I have been digging through the sarama-cluster and sarama source, but I haven't been able to find a way to achieve this.

**Comment by dim** [comment]
I don't quite understand your process, seems like you are trying to do something Kafka is not necessarily designed to do. 

> At the start of each minute I mark an offset from 5 minutes ago, so if the service is restarted it can re-calculate the summary data.

I don't really have much insight into your system, hence it's hard to give architectural advice, but why don't you simply mark the offset of what you have actually processed and committed. I assume your events have timestamps, you could easily then just skip everything that is outside the relevant period.

You could:

1. buffer messages for 5 minutes
2. process accumulated messages, store result or whatever the goal
3. commit the offset the last processed message

If you e.g. want to process the last 5 minutes, but every minute, you will need 5 separate in-memory buffers and you should only mark messages that you flush from your oldest buffer (as you will not need them again). if your service dies or restarts, you can easily re-fill the 5 buffers, as long as you have timestamp info on your messages.

Closing for now,
Dim

**Comment by recurser** [comment]
Thanks for the feedback @dim - appreciate it. 

> why don't you simply mark the offset of what you have actually processed and committed

Yes that's what we're doing. The issue is that after rebalancing, we are no longer receiving data from the same partitions, so our buffered data is no longer valid. We may have 5 minutes of data for partition `1`, and suddenly start getting data for partition `2` after a rebalance. At this point we need to travel back in time to the last offset for partition `2` to refill the buffer.

So in effect we'd like to do something like this:

```
for message := range consumer.Messages() {
  if didRebalance == true {
    // Start to re-read consumer.Messages() from the last offset 5 mins ago, so we can refill our buffer.
  }
  
  // Buffer summary data here.
}
```

I can't figure out how to jump back to the last offset while looping over `for message :=` in the case that a rebalance has occurred. Reconnecting to Kafka will start from the last offset as required, but will cause a rebalance in other consumers and leave us with the same problem in another consumer.

Probably this is not something that sarama-cluster is designed to handle, since it's a fairly edge case - I'll do some more digging in the sarama offset manager and see if we can do this at a lower level.

Thanks!

**Comment by dim** [comment]
Hmm, from what you are saying, sarama-cluster may not be the right tool for
you. The idea behind it is to make consumers stateless and unaware of
partitions.

There is currently no (simple) way to assign a partition to a particular
consumer. You could implement your own PartitionStrategy which could use
some form of consistent hashing, but it would be an approximation at best.

By the sounds of it, you know your exact number of partitions and the
number of consumer instances, so why don't you just use sarama directly?
There you can exactly specify what topic/partition you want to consume. The
downside is that you would have to monitor/supervise your consumers more
carefully, to ensure they recover on failures, but that seems a much more
straightforward task.

Finally, if I were to do something like this, I wouldn't accumulate state
inside consumers but rather consume the whole topic and
buffer/pre-accumulate the data e.g. in Redis (1 key per minute). I would
then run a separate, periodic task to process the last 5 keys.

Hope that helps!

**Comment by recurser** [comment]
> By the sounds of it, you know your exact number of partitions and the
number of consumer instances, so why don't you just use sarama directly?

Thanks @dim, this does seems like the simplest solution - I'm going to go with it 👍 

> Finally, if I were to do something like this, I wouldn't accumulate state
inside consumers but rather consume the whole topic and
buffer/pre-accumulate the data e.g. in Redis (1 key per minute).

I've been going back and forth between redis and local-memory storage, but another aspect of the app requires a moving window of the last minute's data (ie storage every second), and the volume of metrics seemed like it would cause a lot of network requests to redis. This would definitely simplify the consumer implementation though, so I'll give it another look.

Thanks again for your your thoughts - much appreciated!
