### ISSUE TITLE
Get unreaded messages

### ISSUE THREAD

**Issue by lfirek** [bsm/sarama-cluster#83]
Hello,

It's possible to get unread messages from kafka by groupID from last commit?

When I'm using for mark messages as read
```
consumer.MarkOffset(msg, "used")
```
and configuration
```
configConsumer.Consumer.Offsets.Initial = sarama.OffsetOldest
```
It's works but it's really hard to get oldest messages (I must change groupID) and it's not handy for me.

How read marked metadata for message?

**Comment by dim** [comment]
Sorry, I don't understand the question. Do you want to reset your stored offsets and re-start consuming from start? This sounds like a use case for using https://github.com/Shopify/sarama directly and not sarama cluster.
