### ISSUE TITLE
Does cluster.NewConsumer  support regex pattern like official kafka java client does

### ISSUE THREAD

**Issue by chandradeepak** [bsm/sarama-cluster#84]
`void	  subscribe(java.util.regex.Pattern pattern, ConsumerRebalanceListener listener)`
Subscribe to all topics matching specified pattern to get dynamically assigned partitions.

https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

If not is there a way to do that.

**Comment by dim** [comment]
So at the moment, sarama cluster client is unable to auto-discover new topics at runtime (which is where the regexp functionality would make most sense). I will see if I can add something ...

**Comment by dim** [comment]
This would be a prerequisite for the regex subscription: https://github.com/bsm/sarama-cluster/pull/85

**Comment by chandradeepak** [comment]
thanks for the branch . i will try it out. closing this issue now.

**Comment by dim** [comment]
Implemented in https://github.com/bsm/sarama-cluster/pull/102 (will be merged soon)
