### ISSUE TITLE
cluster_test broken due to a change in sarama's sync_processor's config handling

### ISSUE THREAD

**Issue by elakito** [bsm/sarama-cluster#89]
I am getting the following error from cluster_test.go
Expected error:
      <sarama.ConfigurationError>: Producer.Return.Successes must be true to be used in a SyncProducer
      kafka: invalid configuration (Producer.Return.Successes must be true to be used in a SyncProducer)
  not to have occurred

This seems to be the side effect of the following change in Shopify/sarama

https://github.com/Shopify/sarama/commit/f0062da5ae1a62f7841e563a244e11a5ad9b96d7

which added verifyProducerConfig in sync_producer that rejects the config if its Producer.Return.Successes is not set to true.

I verified that initializing testClient in cluster_test.go with an appropriate config object that has this property being set solved this problem.

I am not sure if sarama's check became too strict and would be preferably loosened.

Please let me know how we should proceed.

regards, aki

**Comment by dim** [comment]
Hmm, it looks like an unreleased version as my tests with Sarama 1.10.x pass. We use semver to keep in sync with sarama's developments, but I will nevertheless merge your PR, thanks.
