### ISSUE TITLE
Consumer failing to claim a partition when messages are published after subscription starts

### ISSUE THREAD

**Issue by elakito** [bsm/sarama-cluster#94]
I am experimenting the problem of a consumer sometimes failing to claim a partition. It seems this almost always happens when a consumer subscribes to a previously non existent topic and later some messages are published to this topic.

The below test program demonstrates this behavior with the current sarama-cluster master.
https://gist.github.com/elakito/8c33dd318def85f6544a3ba799e34c36

I am not sure if this is an issue or there is some property that needs to be set to avoid this problem.

Any advice will be appreciated.

regards, aki

**Comment by dim** [comment]
> always happens when a consumer subscribes to a previously non existent topic and later some messages are published to this topic
sorry, I don't quite understand this. at the moment the current master doesn't support subscriptions to topics that don't exist (yet). there is a PR to fix this in the future and periodically check for new topics

**Comment by elakito** [comment]
@dim thanks. Your description answers my question and explains the behavior that I observed. I will be interested in the mentioned PR if that is already in some repo/branch.

regards, aki

**Comment by dim** [comment]
sorry, it was mentioned in this issue https://github.com/bsm/sarama-cluster/issues/48. I did some pre-work  but I haven't had time to continue yet
