### ISSUE TITLE
Error when running `go install`

### ISSUE THREAD

**Issue by jayncoke** [bsm/sarama-cluster#97]
After I run `go get` when importing "github.com/bsm/sarama-cluster", I get this error when running `go install`:

```
# github.com/bsm/sarama-cluster
../../bsm/sarama-cluster/consumer.go:101: c.csmr.HighWaterMarks undefined (type sarama.Consumer has no field or method HighWaterMarks)
```

**Comment by nsd20463** [comment]
That method was added a few monthsa ago. Perhaps you haven't updated your sarama package in a while.
  go get -u -v ./...

**Comment by jayncoke** [comment]
Oh, yeah you're right. Needed to do an update on the package. Derp.

That did it! Thanks!
